// Generated by Haxe
(function (console, $global) { "use strict";
var $estr = function() { return js_Boot.__string_rec(this,''); };
function $extend(from, fields) {
	function Inherit() {} Inherit.prototype = from; var proto = new Inherit();
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var doom_IComponent = function() { };
doom_IComponent.__name__ = ["doom","IComponent"];
doom_IComponent.prototype = {
	__class__: doom_IComponent
};
var doom_ComponentBase = function(children) {
	this.children = null == children?[]:children;
	this.node = this.render();
};
doom_ComponentBase.__name__ = ["doom","ComponentBase"];
doom_ComponentBase.__interfaces__ = [doom_IComponent];
doom_ComponentBase.prototype = {
	init: function() {
		this.element = doom_HtmlNode.toHtml(this.node);
	}
	,render: function() {
		throw new thx_error_AbstractMethod({ fileName : "ComponentBase.hx", lineNumber : 24, className : "doom.ComponentBase", methodName : "render"});
	}
	,didMount: function() {
	}
	,didRefresh: function() {
	}
	,didUnmount: function() {
	}
	,toString: function() {
		var cls = Type.getClassName(js_Boot.getClass(this)).split(".").pop();
		return "" + cls + "(" + thx_Strings.ellipsisMiddle(doom__$Node_Node_$Impl_$.toString(this.node),80,"...") + ")";
	}
	,updateNode: function(oldNode) {
		var newNode = this.render();
		switch(newNode[1]) {
		case 0:
			break;
		case 3:
			break;
		default:
			throw new thx_Error("Component " + this.toString() + " must return only element nodes",null,{ fileName : "ComponentBase.hx", lineNumber : 41, className : "doom.ComponentBase", methodName : "updateNode"});
		}
		var patches = doom__$Node_Node_$Impl_$.diff(oldNode,newNode);
		doom_HtmlNode.applyPatches(patches,this.element);
		this.node = newNode;
	}
	,__class__: doom_ComponentBase
};
var Doom = function() { };
Doom.__name__ = ["Doom"];
Doom.mount = function(component,ref) {
	if(null == ref) throw new js__$Boot_HaxeError("reference element is set to null");
	ref.innerHTML = "";
	component.init();
	ref.appendChild(component.element);
	thx_Timer.immediate($bind(component,component.didMount));
};
Doom.__super__ = doom_ComponentBase;
Doom.prototype = $extend(doom_ComponentBase.prototype,{
	__class__: Doom
});
var EReg = function(r,opt) {
	opt = opt.split("u").join("");
	this.r = new RegExp(r,opt);
};
EReg.__name__ = ["EReg"];
EReg.prototype = {
	match: function(s) {
		if(this.r.global) this.r.lastIndex = 0;
		this.r.m = this.r.exec(s);
		this.r.s = s;
		return this.r.m != null;
	}
	,matched: function(n) {
		if(this.r.m != null && n >= 0 && n < this.r.m.length) return this.r.m[n]; else throw new js__$Boot_HaxeError("EReg::matched");
	}
	,__class__: EReg
};
var HxOverrides = function() { };
HxOverrides.__name__ = ["HxOverrides"];
HxOverrides.dateStr = function(date) {
	var m = date.getMonth() + 1;
	var d = date.getDate();
	var h = date.getHours();
	var mi = date.getMinutes();
	var s = date.getSeconds();
	return date.getFullYear() + "-" + (m < 10?"0" + m:"" + m) + "-" + (d < 10?"0" + d:"" + d) + " " + (h < 10?"0" + h:"" + h) + ":" + (mi < 10?"0" + mi:"" + mi) + ":" + (s < 10?"0" + s:"" + s);
};
HxOverrides.cca = function(s,index) {
	var x = s.charCodeAt(index);
	if(x != x) return undefined;
	return x;
};
HxOverrides.substr = function(s,pos,len) {
	if(len == null) len = s.length; else if(len < 0) {
		if(pos == 0) len = s.length + len; else return "";
	}
	if(pos < 0) {
		pos = s.length + pos;
		if(pos < 0) pos = 0;
	}
	return s.substr(pos,len);
};
HxOverrides.indexOf = function(a,obj,i) {
	var len = a.length;
	if(i < 0) {
		i += len;
		if(i < 0) i = 0;
	}
	while(i < len) {
		if(a[i] === obj) return i;
		i++;
	}
	return -1;
};
HxOverrides.remove = function(a,obj) {
	var i = HxOverrides.indexOf(a,obj,0);
	if(i == -1) return false;
	a.splice(i,1);
	return true;
};
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var Main = function() { };
Main.__name__ = ["Main"];
Main.main = function() {
	var tmp = Main.getFilterFromHash();
	var store = lies_Store.create(function(state,action) {
		return { _0 : todomvc_data_Reducers.todoApp(state,action), _1 : []};
	},{ visibilityFilter : tmp, todos : Main.getTodosFromLocalStorage()});
	var f = function(state1) {
		window.localStorage.setItem("TodoMVC-Doom",JSON.stringify(state1.todos));
	};
	store.subscribe(function(state3,_,_1) {
		f(state3);
	});
	var f1 = function(state2) {
		var tmp1;
		var _g = state2.visibilityFilter;
		switch(_g[1]) {
		case 2:
			tmp1 = "/active";
			break;
		case 1:
			tmp1 = "/completed";
			break;
		default:
			tmp1 = "";
		}
		window.location.hash = tmp1;
	};
	store.subscribe(function(state4,_2,_3) {
		f1(state4);
	});
	var f2 = function(action1) {
		window.console.log(thx_Enums.string(action1));
	};
	store.subscribe(function(_4,_5,action2) {
		f2(action2);
	});
	Doom.mount(new todomvc_view_App(store,{ }),dots_Query.find("section.todoapp"));
};
Main.getFilterFromHash = function() {
	var hash = thx_Strings.trimCharsLeft(window.location.hash,"#");
	switch(hash) {
	case "/active":
		return todomvc_data_VisibilityFilter.ShowActive;
	case "/completed":
		return todomvc_data_VisibilityFilter.ShowCompleted;
	default:
		return todomvc_data_VisibilityFilter.ShowAll;
	}
};
Main.getTodosFromLocalStorage = function() {
	var v = window.localStorage.getItem("TodoMVC-Doom");
	if(v != null && v.length > 0) return JSON.parse(v); else return [];
};
Math.__name__ = ["Math"];
var Reflect = function() { };
Reflect.__name__ = ["Reflect"];
Reflect.field = function(o,field) {
	try {
		return o[field];
	} catch( e ) {
		haxe_CallStack.lastException = e;
		return null;
	}
};
Reflect.fields = function(o) {
	var a = [];
	if(o != null) {
		var hasOwnProperty = Object.prototype.hasOwnProperty;
		for( var f in o ) {
		if(f != "__id__" && f != "hx__closures__" && hasOwnProperty.call(o,f)) a.push(f);
		}
	}
	return a;
};
var Std = function() { };
Std.__name__ = ["Std"];
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
Std.parseInt = function(x) {
	var v = parseInt(x,10);
	if(v == 0 && (HxOverrides.cca(x,1) == 120 || HxOverrides.cca(x,1) == 88)) v = parseInt(x);
	if(isNaN(v)) return null;
	return v;
};
var StringBuf = function() {
	this.b = "";
};
StringBuf.__name__ = ["StringBuf"];
StringBuf.prototype = {
	__class__: StringBuf
};
var StringTools = function() { };
StringTools.__name__ = ["StringTools"];
StringTools.isSpace = function(s,pos) {
	var c = HxOverrides.cca(s,pos);
	if(!(c > 8 && c < 14)) return c == 32; else return true;
};
StringTools.ltrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,r)) ++r;
	if(r > 0) return HxOverrides.substr(s,r,l - r); else return s;
};
StringTools.rtrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,l - r - 1)) ++r;
	if(r > 0) return HxOverrides.substr(s,0,l - r); else return s;
};
StringTools.trim = function(s) {
	return StringTools.ltrim(StringTools.rtrim(s));
};
StringTools.replace = function(s,sub,by) {
	return s.split(sub).join(by);
};
var ValueType = { __ename__ : ["ValueType"], __constructs__ : ["TNull","TInt","TFloat","TBool","TObject","TFunction","TClass","TEnum","TUnknown"] };
ValueType.TNull = ["TNull",0];
ValueType.TNull.toString = $estr;
ValueType.TNull.__enum__ = ValueType;
ValueType.TInt = ["TInt",1];
ValueType.TInt.toString = $estr;
ValueType.TInt.__enum__ = ValueType;
ValueType.TFloat = ["TFloat",2];
ValueType.TFloat.toString = $estr;
ValueType.TFloat.__enum__ = ValueType;
ValueType.TBool = ["TBool",3];
ValueType.TBool.toString = $estr;
ValueType.TBool.__enum__ = ValueType;
ValueType.TObject = ["TObject",4];
ValueType.TObject.toString = $estr;
ValueType.TObject.__enum__ = ValueType;
ValueType.TFunction = ["TFunction",5];
ValueType.TFunction.toString = $estr;
ValueType.TFunction.__enum__ = ValueType;
ValueType.TClass = function(c) { var $x = ["TClass",6,c]; $x.__enum__ = ValueType; $x.toString = $estr; return $x; };
ValueType.TEnum = function(e) { var $x = ["TEnum",7,e]; $x.__enum__ = ValueType; $x.toString = $estr; return $x; };
ValueType.TUnknown = ["TUnknown",8];
ValueType.TUnknown.toString = $estr;
ValueType.TUnknown.__enum__ = ValueType;
var Type = function() { };
Type.__name__ = ["Type"];
Type.getClassName = function(c) {
	var a = c.__name__;
	if(a == null) return null;
	return a.join(".");
};
Type.getEnumName = function(e) {
	var a = e.__ename__;
	return a.join(".");
};
Type.createInstance = function(cl,args) {
	var _g = args.length;
	switch(_g) {
	case 0:
		return new cl();
	case 1:
		return new cl(args[0]);
	case 2:
		return new cl(args[0],args[1]);
	case 3:
		return new cl(args[0],args[1],args[2]);
	case 4:
		return new cl(args[0],args[1],args[2],args[3]);
	case 5:
		return new cl(args[0],args[1],args[2],args[3],args[4]);
	case 6:
		return new cl(args[0],args[1],args[2],args[3],args[4],args[5]);
	case 7:
		return new cl(args[0],args[1],args[2],args[3],args[4],args[5],args[6]);
	case 8:
		return new cl(args[0],args[1],args[2],args[3],args[4],args[5],args[6],args[7]);
	default:
		throw new js__$Boot_HaxeError("Too many arguments");
	}
	return null;
};
Type["typeof"] = function(v) {
	var _g = typeof(v);
	switch(_g) {
	case "boolean":
		return ValueType.TBool;
	case "string":
		return ValueType.TClass(String);
	case "number":
		if(Math.ceil(v) == v % 2147483648.0) return ValueType.TInt;
		return ValueType.TFloat;
	case "object":
		if(v == null) return ValueType.TNull;
		var e = v.__enum__;
		if(e != null) return ValueType.TEnum(e);
		var c = js_Boot.getClass(v);
		if(c != null) return ValueType.TClass(c);
		return ValueType.TObject;
	case "function":
		if(v.__name__ || v.__ename__) return ValueType.TObject;
		return ValueType.TFunction;
	case "undefined":
		return ValueType.TNull;
	default:
		return ValueType.TUnknown;
	}
};
Type.enumEq = function(a,b) {
	if(a == b) return true;
	try {
		if(a[0] != b[0]) return false;
		var _g1 = 2;
		var _g = a.length;
		while(_g1 < _g) {
			var i = _g1++;
			if(!Type.enumEq(a[i],b[i])) return false;
		}
		var e = a.__enum__;
		if(e != b.__enum__ || e == null) return false;
	} catch( e1 ) {
		haxe_CallStack.lastException = e1;
		return false;
	}
	return true;
};
var doom__$AttributeValue_AttributeValue_$Impl_$ = {};
doom__$AttributeValue_AttributeValue_$Impl_$.__name__ = ["doom","_AttributeValue","AttributeValue_Impl_"];
doom__$AttributeValue_AttributeValue_$Impl_$.fromString = function(s) {
	return doom_AttributeValueImpl.StringAttribute(s);
};
doom__$AttributeValue_AttributeValue_$Impl_$.fromMap = function(map) {
	var values = [];
	var tmp = map.keys();
	while(tmp.hasNext()) {
		var key = tmp.next();
		if(__map_reserved[key] != null?map.getReserved(key):map.h[key]) values.push(key);
	}
	return doom_AttributeValueImpl.StringAttribute(values.join(" "));
};
doom__$AttributeValue_AttributeValue_$Impl_$.fromBool = function(b) {
	return doom_AttributeValueImpl.BoolAttribute(b);
};
doom__$AttributeValue_AttributeValue_$Impl_$.fromHandler = function(f) {
	if(null == f) return doom_AttributeValueImpl.BoolAttribute(false); else return doom_AttributeValueImpl.EventAttribute(function(e) {
		e.preventDefault();
		f();
	});
};
doom__$AttributeValue_AttributeValue_$Impl_$.fromEventHandler = function(f) {
	if(null == f) return doom_AttributeValueImpl.BoolAttribute(false); else return doom_AttributeValueImpl.EventAttribute(f);
};
doom__$AttributeValue_AttributeValue_$Impl_$.equalsTo = function(this1,that) {
	if(this1 == null) return false; else switch(this1[1]) {
	case 0:
		if(that == null) return false; else switch(that[1]) {
		case 0:
			var a = this1[2];
			var b = that[2];
			return a == b;
		default:
			return false;
		}
		break;
	case 1:
		if(that == null) return false; else switch(that[1]) {
		case 1:
			var a1 = this1[2];
			var b1 = that[2];
			return a1 == b1;
		default:
			return false;
		}
		break;
	default:
		if(that == null) return false; else switch(that[1]) {
		default:
			return false;
		}
	}
};
doom__$AttributeValue_AttributeValue_$Impl_$.notEqualsTo = function(this1,that) {
	return !doom__$AttributeValue_AttributeValue_$Impl_$.equalsTo(this1,that);
};
var doom_AttributeValueImpl = { __ename__ : ["doom","AttributeValueImpl"], __constructs__ : ["BoolAttribute","StringAttribute","EventAttribute"] };
doom_AttributeValueImpl.BoolAttribute = function(b) { var $x = ["BoolAttribute",0,b]; $x.__enum__ = doom_AttributeValueImpl; $x.toString = $estr; return $x; };
doom_AttributeValueImpl.StringAttribute = function(s) { var $x = ["StringAttribute",1,s]; $x.__enum__ = doom_AttributeValueImpl; $x.toString = $estr; return $x; };
doom_AttributeValueImpl.EventAttribute = function(f) { var $x = ["EventAttribute",2,f]; $x.__enum__ = doom_AttributeValueImpl; $x.toString = $estr; return $x; };
var doom_Component = function(api,state,children) {
	this.api = api;
	this.state = state;
	doom_ComponentBase.call(this,children);
};
doom_Component.__name__ = ["doom","Component"];
doom_Component.__super__ = doom_ComponentBase;
doom_Component.prototype = $extend(doom_ComponentBase.prototype,{
	update: function(newState) {
		var oldState = this.state;
		this.state = newState;
		if(!this.shouldRender(oldState,newState)) return;
		this.updateNode(this.node);
	}
	,shouldRender: function(oldState,newState) {
		return true;
	}
	,__class__: doom_Component
});
var doom_HtmlNode = function() { };
doom_HtmlNode.__name__ = ["doom","HtmlNode"];
doom_HtmlNode.toHtml = function(node) {
	var _g = node;
	switch(_g[1]) {
	case 0:
		var children = _g[4];
		var attributes = _g[3];
		var name = _g[2];
		return doom_HtmlNode.createElement(name,attributes,children);
	case 1:
		var text = _g[2];
		return dots_Html.parse(text);
	case 2:
		var text1 = _g[2];
		return window.document.createTextNode(text1);
	case 3:
		var comp = _g[2];
		comp.init();
		thx_Timer.immediate($bind(comp,comp.didMount));
		return comp.element;
	}
};
doom_HtmlNode.createElement = function(name,attributes,children) {
	var colonPos = name.indexOf(":");
	var el;
	if(colonPos > 0) {
		var prefix = name.substring(0,colonPos);
		var name1 = name.substring(colonPos + 1);
		var tmp;
		var _this = Doom.namespaces;
		if(__map_reserved[prefix] != null) tmp = _this.getReserved(prefix); else tmp = _this.h[prefix];
		var ns = tmp;
		if(null == ns) throw new thx_Error("element prefix \"" + prefix + "\" is not associated to any namespace. Add the right namespace to Doom.namespaces.",null,{ fileName : "HtmlNode.hx", lineNumber : 35, className : "doom.HtmlNode", methodName : "createElement"});
		el = window.document.createElementNS(ns,name1);
	} else el = window.document.createElement(name);
	var tmp1 = attributes.keys();
	while(tmp1.hasNext()) {
		var key = tmp1.next();
		var value = __map_reserved[key] != null?attributes.getReserved(key):attributes.h[key];
		if(value != null) switch(value[1]) {
		case 1:
			var s = value[2];
			if(!(null == s || s == "")) {
				var s1 = value[2];
				el.setAttribute(key,s1);
			}
			break;
		case 0:
			var b = value[2];
			if(b) el.setAttribute(key,"");
			break;
		case 2:
			var e = value[2];
			doom_HtmlNode.addEvent(el,key,e);
			break;
		default:
		}
	}
	var _g = 0;
	while(_g < children.length) {
		var child = children[_g];
		++_g;
		var n = doom_HtmlNode.toHtml(child);
		if(null != n) el.appendChild(n);
	}
	return el;
};
doom_HtmlNode.applyPatches = function(patches,node) {
	var _g = 0;
	while(_g < patches.length) {
		var patch = patches[_g];
		++_g;
		doom_HtmlNode.applyPatch(patch,node);
	}
};
doom_HtmlNode.addEvent = function(el,name,handler) {
	el["on" + name] = handler;
};
doom_HtmlNode.applyPatch = function(patch,node) {
	var _g = node.nodeType;
	var p = patch;
	switch(patch[1]) {
	case 4:
		var comp = patch[2];
		comp.didUnmount();
		break;
	case 5:
		var newComp = patch[3];
		var oldComp = patch[2];
		if(thx_Types.sameType(oldComp,newComp)) {
			newComp.element = oldComp.element;
			var migrate = Reflect.field(newComp,"migrate");
			if(null != migrate) migrate.apply(newComp,[oldComp]);
			newComp.didRefresh();
		} else {
			var newComp1 = patch[3];
			var oldComp1 = patch[2];
			newComp1.element = oldComp1.element;
			thx_Timer.immediate($bind(newComp1,newComp1.didMount));
		}
		break;
	case 6:
		var comp1 = patch[2];
		comp1.element = node;
		comp1.didRefresh();
		break;
	case 0:
		switch(_g) {
		case 1:
			var text = patch[2];
			node.appendChild(window.document.createTextNode(text));
			break;
		default:
			throw new thx_Error("cannot apply patch " + Std.string(p) + " on " + Std.string(node),null,{ fileName : "HtmlNode.hx", lineNumber : 146, className : "doom.HtmlNode", methodName : "applyPatch"});
		}
		break;
	case 1:
		switch(_g) {
		case 1:
			var text1 = patch[2];
			node.appendChild(dots_Html.parse(text1));
			break;
		default:
			throw new thx_Error("cannot apply patch " + Std.string(p) + " on " + Std.string(node),null,{ fileName : "HtmlNode.hx", lineNumber : 146, className : "doom.HtmlNode", methodName : "applyPatch"});
		}
		break;
	case 2:
		switch(_g) {
		case 1:
			var name = patch[2];
			var children = patch[4];
			var attributes = patch[3];
			var el = doom_HtmlNode.createElement(name,attributes,children);
			node.appendChild(el);
			break;
		default:
			throw new thx_Error("cannot apply patch " + Std.string(p) + " on " + Std.string(node),null,{ fileName : "HtmlNode.hx", lineNumber : 146, className : "doom.HtmlNode", methodName : "applyPatch"});
		}
		break;
	case 3:
		switch(_g) {
		case 1:
			var comp2 = patch[2];
			comp2.init();
			node.appendChild(comp2.element);
			break;
		default:
			throw new thx_Error("cannot apply patch " + Std.string(p) + " on " + Std.string(node),null,{ fileName : "HtmlNode.hx", lineNumber : 146, className : "doom.HtmlNode", methodName : "applyPatch"});
		}
		break;
	case 7:
		node.parentNode.removeChild(node);
		break;
	case 8:
		switch(_g) {
		case 1:
			var name1 = patch[2];
			node.removeAttribute(name1);
			break;
		default:
			throw new thx_Error("cannot apply patch " + Std.string(p) + " on " + Std.string(node),null,{ fileName : "HtmlNode.hx", lineNumber : 146, className : "doom.HtmlNode", methodName : "applyPatch"});
		}
		break;
	case 9:
		switch(_g) {
		case 1:
			var name2 = patch[2];
			var value = patch[3];
			if(value == null) node.removeAttribute(name2); else switch(value[1]) {
			case 1:
				var s = value[2];
				if(s == null || s == "") node.removeAttribute(name2); else {
					var s1 = value[2];
					node.setAttribute(name2,s1);
				}
				break;
			case 0:
				var b = value[2];
				if(b) node.setAttribute(name2,name2); else node.removeAttribute(name2);
				break;
			case 2:
				var e = value[2];
				doom_HtmlNode.addEvent(node,name2,e);
				break;
			}
			break;
		default:
			throw new thx_Error("cannot apply patch " + Std.string(p) + " on " + Std.string(node),null,{ fileName : "HtmlNode.hx", lineNumber : 146, className : "doom.HtmlNode", methodName : "applyPatch"});
		}
		break;
	case 10:
		var children1 = patch[4];
		var attributes1 = patch[3];
		var name3 = patch[2];
		var parent = node.parentNode;
		var el1 = doom_HtmlNode.createElement(name3,attributes1,children1);
		parent.replaceChild(el1,node);
		break;
	case 13:
		var comp3 = patch[2];
		var parent1 = node.parentNode;
		comp3.init();
		thx_Timer.immediate($bind(comp3,comp3.didMount));
		parent1.replaceChild(comp3.element,node);
		break;
	case 11:
		var text2 = patch[2];
		var parent2 = node.parentNode;
		parent2.replaceChild(window.document.createTextNode(text2),node);
		break;
	case 12:
		var raw = patch[2];
		var parent3 = node.parentNode;
		parent3.replaceChild(dots_Html.parse(raw),node);
		break;
	case 14:
		switch(_g) {
		case 3:
			var newcontent = patch[2];
			if(node.parentNode.nodeName == "TEXTAREA") node.parentNode.value = newcontent; else node.nodeValue = newcontent;
			break;
		case 8:
			var newcontent1 = patch[2];
			if(node.parentNode.nodeName == "TEXTAREA") node.parentNode.value = newcontent1; else node.nodeValue = newcontent1;
			break;
		default:
			throw new thx_Error("cannot apply patch " + Std.string(p) + " on " + Std.string(node),null,{ fileName : "HtmlNode.hx", lineNumber : 146, className : "doom.HtmlNode", methodName : "applyPatch"});
		}
		break;
	case 15:
		switch(_g) {
		case 1:
			var index = patch[2];
			var patches = patch[3];
			var n = node.childNodes.item(index);
			if(null != n) doom_HtmlNode.applyPatches(patches,n);
			break;
		default:
			throw new thx_Error("cannot apply patch " + Std.string(p) + " on " + Std.string(node),null,{ fileName : "HtmlNode.hx", lineNumber : 146, className : "doom.HtmlNode", methodName : "applyPatch"});
		}
		break;
	}
};
var doom__$Node_Node_$Impl_$ = {};
doom__$Node_Node_$Impl_$.__name__ = ["doom","_Node","Node_Impl_"];
doom__$Node_Node_$Impl_$.el = function(name,attributes,children,child) {
	if(null == attributes) attributes = new haxe_ds_StringMap();
	if(null == children) children = [];
	if(null != child) children.push(child);
	return doom_NodeImpl.Element(name,attributes,children);
};
doom__$Node_Node_$Impl_$.diffAttributes = function(a,b) {
	var ka = thx__$Set_Set_$Impl_$.createString(thx_Iterators.toArray(a.keys()));
	var kb = thx__$Set_Set_$Impl_$.createString(thx_Iterators.toArray(b.keys()));
	var result = thx__$Set_Set_$Impl_$.copy(ka);
	var tmp2 = $iterator(thx__$Set_Set_$Impl_$)(kb);
	while(tmp2.hasNext()) {
		var item = tmp2.next();
		result.remove(item);
	}
	var result1 = thx__$Set_Set_$Impl_$.copy(kb);
	var tmp3 = $iterator(thx__$Set_Set_$Impl_$)(ka);
	while(tmp3.hasNext()) {
		var item1 = tmp3.next();
		result1.remove(item1);
	}
	var result2 = thx__$Set_Set_$Impl_$.empty(ka);
	var tmp4 = $iterator(thx__$Set_Set_$Impl_$)(ka);
	while(tmp4.hasNext()) {
		var item2 = tmp4.next();
		var tmp5;
		var _this = kb;
		if(__map_reserved[item2] != null) tmp5 = _this.existsReserved(item2); else tmp5 = _this.h.hasOwnProperty(item2);
		if(tmp5) {
			var _this1 = result2;
			if(__map_reserved[item2] != null) _this1.setReserved(item2,true); else _this1.h[item2] = true;
		}
	}
	var _e = result;
	var tmp = function(f) {
		return thx__$Set_Set_$Impl_$.map(_e,f);
	};
	var _e1 = result2;
	var _e2 = (function(predicate) {
		return thx__$Set_Set_$Impl_$.filter(_e1,predicate);
	})(function(_) {
		return doom__$AttributeValue_AttributeValue_$Impl_$.notEqualsTo(__map_reserved[_] != null?a.getReserved(_):a.h[_],__map_reserved[_] != null?b.getReserved(_):b.h[_]);
	});
	var tmp1 = (function(f1) {
		return thx__$Set_Set_$Impl_$.map(_e2,f1);
	})(function(_1) {
		return doom_Patch.SetAttribute(_1,__map_reserved[_1] != null?b.getReserved(_1):b.h[_1]);
	});
	var _e3 = result1;
	return tmp(function(_2) {
		return doom_Patch.RemoveAttribute(_2);
	}).concat(tmp1).concat((function(f2) {
		return thx__$Set_Set_$Impl_$.map(_e3,f2);
	})(function(_3) {
		return doom_Patch.SetAttribute(_3,__map_reserved[_3] != null?b.getReserved(_3):b.h[_3]);
	}));
};
doom__$Node_Node_$Impl_$.diffAdd = function(node) {
	switch(node[1]) {
	case 0:
		var c = node[4];
		var a = node[3];
		var n = node[2];
		return [doom_Patch.AddElement(n,a,c)];
	case 2:
		var t = node[2];
		return [doom_Patch.AddText(t)];
	case 1:
		var t1 = node[2];
		return [doom_Patch.AddRaw(t1)];
	case 3:
		var comp = node[2];
		return [doom_Patch.AddComponent(comp)];
	}
};
doom__$Node_Node_$Impl_$.diffNodes = function(a,b) {
	var min;
	var a1 = a.length;
	var b1 = b.length;
	if(a1 < b1) min = a1; else min = b1;
	var result = [];
	var counter = 0;
	var _g1 = min;
	var _g = a.length;
	while(_g1 < _g) {
		++_g1;
		var tmp = a.length;
		++counter;
		result.push(doom_Patch.PatchChild(tmp - counter,[doom_Patch.Remove]));
	}
	var _g11 = min;
	var _g2 = b.length;
	while(_g11 < _g2) {
		var i = _g11++;
		result = result.concat(doom__$Node_Node_$Impl_$.diffAdd(b[i]));
	}
	var _g3 = 0;
	while(_g3 < min) {
		var i1 = _g3++;
		var diff = doom__$Node_Node_$Impl_$.diff(a[i1],b[i1]);
		if(diff.length > 0) result.push(doom_Patch.PatchChild(i1,diff));
	}
	return result;
};
doom__$Node_Node_$Impl_$.diff = function(this1,that) {
	var p;
	switch(this1[1]) {
	case 3:
		switch(that[1]) {
		case 3:
			var old = this1[2];
			var comp = that[2];
			p = [doom_Patch.MigrateComponentToComponent(old,comp)];
			break;
		default:
			var comp1 = this1[2];
			p = [doom_Patch.DestroyComponent(comp1)];
		}
		break;
	default:
		switch(that[1]) {
		case 3:
			var comp2 = that[2];
			p = [doom_Patch.MigrateElementToComponent(comp2)];
			break;
		default:
			p = [];
		}
	}
	var tmp;
	switch(this1[1]) {
	case 3:
		switch(that[1]) {
		case 3:
			var old1 = this1[2];
			var comp3 = that[2];
			tmp = doom__$Node_Node_$Impl_$.diff(old1.node,comp3.node);
			break;
		case 0:
			var c2 = that[4];
			var a2 = that[3];
			var n2 = that[2];
			tmp = [doom_Patch.ReplaceWithElement(n2,a2,c2)];
			break;
		case 2:
			var t = that[2];
			tmp = [doom_Patch.ReplaceWithText(t)];
			break;
		case 1:
			var t1 = that[2];
			tmp = [doom_Patch.ReplaceWithRaw(t1)];
			break;
		}
		break;
	case 0:
		switch(that[1]) {
		case 3:
			var comp4 = that[2];
			tmp = [doom_Patch.ReplaceWithComponent(comp4)];
			break;
		case 0:
			var n1 = this1[2];
			var c21 = that[4];
			var a21 = that[3];
			var n21 = that[2];
			if(n1 != n21) tmp = [doom_Patch.ReplaceWithElement(n21,a21,c21)]; else {
				var c1 = this1[4];
				var a1 = this1[3];
				var c22 = that[4];
				var a22 = that[3];
				tmp = doom__$Node_Node_$Impl_$.diffAttributes(a1,a22).concat(doom__$Node_Node_$Impl_$.diffNodes(c1,c22));
			}
			break;
		case 2:
			var t2 = that[2];
			tmp = [doom_Patch.ReplaceWithText(t2)];
			break;
		case 1:
			var t3 = that[2];
			tmp = [doom_Patch.ReplaceWithRaw(t3)];
			break;
		}
		break;
	case 2:
		switch(that[1]) {
		case 3:
			var comp5 = that[2];
			tmp = [doom_Patch.ReplaceWithComponent(comp5)];
			break;
		case 0:
			var c23 = that[4];
			var a23 = that[3];
			var n22 = that[2];
			tmp = [doom_Patch.ReplaceWithElement(n22,a23,c23)];
			break;
		case 2:
			var t11 = this1[2];
			var t21 = that[2];
			if(t11 != t21) tmp = [doom_Patch.ContentChanged(t21)]; else tmp = [];
			break;
		case 1:
			var t4 = that[2];
			tmp = [doom_Patch.ReplaceWithRaw(t4)];
			break;
		}
		break;
	default:
		switch(that[1]) {
		case 3:
			var comp6 = that[2];
			tmp = [doom_Patch.ReplaceWithComponent(comp6)];
			break;
		case 0:
			var c24 = that[4];
			var a24 = that[3];
			var n23 = that[2];
			tmp = [doom_Patch.ReplaceWithElement(n23,a24,c24)];
			break;
		case 2:
			var t5 = that[2];
			tmp = [doom_Patch.ReplaceWithText(t5)];
			break;
		case 1:
			var t6 = that[2];
			tmp = [doom_Patch.ReplaceWithRaw(t6)];
			break;
		}
	}
	return p.concat(tmp);
};
doom__$Node_Node_$Impl_$.toString = function(this1) {
	return doom_XmlNode.toString(this1);
};
var doom_NodeImpl = { __ename__ : ["doom","NodeImpl"], __constructs__ : ["Element","Raw","Text","ComponentNode"] };
doom_NodeImpl.Element = function(name,attributes,children) { var $x = ["Element",0,name,attributes,children]; $x.__enum__ = doom_NodeImpl; $x.toString = $estr; return $x; };
doom_NodeImpl.Raw = function(text) { var $x = ["Raw",1,text]; $x.__enum__ = doom_NodeImpl; $x.toString = $estr; return $x; };
doom_NodeImpl.Text = function(text) { var $x = ["Text",2,text]; $x.__enum__ = doom_NodeImpl; $x.toString = $estr; return $x; };
doom_NodeImpl.ComponentNode = function(comp) { var $x = ["ComponentNode",3,comp]; $x.__enum__ = doom_NodeImpl; $x.toString = $estr; return $x; };
var doom_Patch = { __ename__ : ["doom","Patch"], __constructs__ : ["AddText","AddRaw","AddElement","AddComponent","DestroyComponent","MigrateComponentToComponent","MigrateElementToComponent","Remove","RemoveAttribute","SetAttribute","ReplaceWithElement","ReplaceWithText","ReplaceWithRaw","ReplaceWithComponent","ContentChanged","PatchChild"] };
doom_Patch.AddText = function(text) { var $x = ["AddText",0,text]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.AddRaw = function(text) { var $x = ["AddRaw",1,text]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.AddElement = function(name,attributes,children) { var $x = ["AddElement",2,name,attributes,children]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.AddComponent = function(comp) { var $x = ["AddComponent",3,comp]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.DestroyComponent = function(comp) { var $x = ["DestroyComponent",4,comp]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.MigrateComponentToComponent = function(oldComp,newComp) { var $x = ["MigrateComponentToComponent",5,oldComp,newComp]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.MigrateElementToComponent = function(comp) { var $x = ["MigrateElementToComponent",6,comp]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.Remove = ["Remove",7];
doom_Patch.Remove.toString = $estr;
doom_Patch.Remove.__enum__ = doom_Patch;
doom_Patch.RemoveAttribute = function(name) { var $x = ["RemoveAttribute",8,name]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.SetAttribute = function(name,value) { var $x = ["SetAttribute",9,name,value]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.ReplaceWithElement = function(name,attributes,children) { var $x = ["ReplaceWithElement",10,name,attributes,children]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.ReplaceWithText = function(text) { var $x = ["ReplaceWithText",11,text]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.ReplaceWithRaw = function(raw) { var $x = ["ReplaceWithRaw",12,raw]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.ReplaceWithComponent = function(comp) { var $x = ["ReplaceWithComponent",13,comp]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.ContentChanged = function(newcontent) { var $x = ["ContentChanged",14,newcontent]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.PatchChild = function(index,patches) { var $x = ["PatchChild",15,index,patches]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
var doom_XmlNode = function() { };
doom_XmlNode.__name__ = ["doom","XmlNode"];
doom_XmlNode.toString = function(node) {
	var _g = node;
	switch(_g[1]) {
	case 0:
		var children = _g[4];
		var attributes = _g[3];
		var name = _g[2];
		var buf = "<" + name + doom_XmlNode.attributesToString(attributes);
		if(children.length == 0) buf += "/>"; else {
			buf += ">";
			buf += children.map(function(_) {
				return doom_XmlNode.toString(_);
			}).join("");
			buf += "</" + name + ">";
		}
		return buf;
	case 2:
		var text = _g[2];
		return text;
	case 1:
		var text1 = _g[2];
		return text1;
	case 3:
		var comp = _g[2];
		return doom_XmlNode.toString(comp.node);
	}
};
doom_XmlNode.attributesToString = function(attributes) {
	var buf = "";
	var tmp = attributes.keys();
	while(tmp.hasNext()) {
		var key = tmp.next();
		var value = __map_reserved[key] != null?attributes.getReserved(key):attributes.h[key];
		switch(value[1]) {
		case 1:
			var s = value[2];
			if(s != null && s.length > 0) buf += " " + key + "=\"" + StringTools.replace(s,"\"","&quot;") + "\"";
			break;
		case 0:
			var b = value[2];
			if(b) buf += " " + key + "=\"" + key + "\"";
			break;
		default:
		}
	}
	return buf;
};
var dots_Html = function() { };
dots_Html.__name__ = ["dots","Html"];
dots_Html.parseNodes = function(html) {
	if(!dots_Html.pattern.match(html)) throw new js__$Boot_HaxeError("Invalid pattern \"" + html + "\"");
	var el;
	var _g = dots_Html.pattern.matched(1).toLowerCase();
	switch(_g) {
	case "tbody":case "thead":
		el = window.document.createElement("table");
		break;
	case "td":case "th":
		el = window.document.createElement("tr");
		break;
	case "tr":
		el = window.document.createElement("tbody");
		break;
	default:
		el = window.document.createElement("div");
	}
	el.innerHTML = html;
	return el.childNodes;
};
dots_Html.parse = function(html) {
	return dots_Html.parseNodes(html)[0];
};
var dots_Query = function() { };
dots_Query.__name__ = ["dots","Query"];
dots_Query.find = function(selector,ctx) {
	return (ctx != null?ctx:dots_Query.doc).querySelector(selector);
};
var haxe_StackItem = { __ename__ : ["haxe","StackItem"], __constructs__ : ["CFunction","Module","FilePos","Method","LocalFunction"] };
haxe_StackItem.CFunction = ["CFunction",0];
haxe_StackItem.CFunction.toString = $estr;
haxe_StackItem.CFunction.__enum__ = haxe_StackItem;
haxe_StackItem.Module = function(m) { var $x = ["Module",1,m]; $x.__enum__ = haxe_StackItem; $x.toString = $estr; return $x; };
haxe_StackItem.FilePos = function(s,file,line) { var $x = ["FilePos",2,s,file,line]; $x.__enum__ = haxe_StackItem; $x.toString = $estr; return $x; };
haxe_StackItem.Method = function(classname,method) { var $x = ["Method",3,classname,method]; $x.__enum__ = haxe_StackItem; $x.toString = $estr; return $x; };
haxe_StackItem.LocalFunction = function(v) { var $x = ["LocalFunction",4,v]; $x.__enum__ = haxe_StackItem; $x.toString = $estr; return $x; };
var haxe_CallStack = function() { };
haxe_CallStack.__name__ = ["haxe","CallStack"];
haxe_CallStack.getStack = function(e) {
	if(e == null) return [];
	var oldValue = Error.prepareStackTrace;
	Error.prepareStackTrace = function(error,callsites) {
		var stack = [];
		var _g = 0;
		while(_g < callsites.length) {
			var site = callsites[_g];
			++_g;
			if(haxe_CallStack.wrapCallSite != null) site = haxe_CallStack.wrapCallSite(site);
			var method = null;
			var fullName = site.getFunctionName();
			if(fullName != null) {
				var idx = fullName.lastIndexOf(".");
				if(idx >= 0) {
					var className = HxOverrides.substr(fullName,0,idx);
					var methodName = HxOverrides.substr(fullName,idx + 1,null);
					method = haxe_StackItem.Method(className,methodName);
				}
			}
			stack.push(haxe_StackItem.FilePos(method,site.getFileName(),site.getLineNumber()));
		}
		return stack;
	};
	var a = haxe_CallStack.makeStack(e.stack);
	Error.prepareStackTrace = oldValue;
	return a;
};
haxe_CallStack.callStack = function() {
	try {
		throw new Error();
	} catch( e ) {
		haxe_CallStack.lastException = e;
		if (e instanceof js__$Boot_HaxeError) e = e.val;
		var a = haxe_CallStack.getStack(e);
		a.shift();
		return a;
	}
};
haxe_CallStack.exceptionStack = function() {
	return haxe_CallStack.getStack(haxe_CallStack.lastException);
};
haxe_CallStack.toString = function(stack) {
	var b = new StringBuf();
	var _g = 0;
	while(_g < stack.length) {
		var s = stack[_g];
		++_g;
		b.b += "\nCalled from ";
		haxe_CallStack.itemToString(b,s);
	}
	return b.b;
};
haxe_CallStack.itemToString = function(b,s) {
	switch(s[1]) {
	case 0:
		b.b += "a C function";
		break;
	case 1:
		var m = s[2];
		b.b += "module ";
		b.b += m == null?"null":"" + m;
		break;
	case 2:
		var line = s[4];
		var file = s[3];
		var s1 = s[2];
		if(s1 != null) {
			haxe_CallStack.itemToString(b,s1);
			b.b += " (";
		}
		b.b += file == null?"null":"" + file;
		b.b += " line ";
		b.b += line == null?"null":"" + line;
		if(s1 != null) b.b += ")";
		break;
	case 3:
		var meth = s[3];
		var cname = s[2];
		b.b += cname == null?"null":"" + cname;
		b.b += ".";
		b.b += meth == null?"null":"" + meth;
		break;
	case 4:
		var n = s[2];
		b.b += "local function #";
		b.b += n == null?"null":"" + n;
		break;
	}
};
haxe_CallStack.makeStack = function(s) {
	if(s == null) return []; else if(typeof(s) == "string") {
		var stack = s.split("\n");
		if(stack[0] == "Error") stack.shift();
		var m = [];
		var rie10 = new EReg("^   at ([A-Za-z0-9_. ]+) \\(([^)]+):([0-9]+):([0-9]+)\\)$","");
		var _g = 0;
		while(_g < stack.length) {
			var line = stack[_g];
			++_g;
			if(rie10.match(line)) {
				var path = rie10.matched(1).split(".");
				var meth = path.pop();
				var file = rie10.matched(2);
				var line1 = Std.parseInt(rie10.matched(3));
				m.push(haxe_StackItem.FilePos(meth == "Anonymous function"?haxe_StackItem.LocalFunction():meth == "Global code"?null:haxe_StackItem.Method(path.join("."),meth),file,line1));
			} else m.push(haxe_StackItem.Module(StringTools.trim(line)));
		}
		return m;
	} else return s;
};
var haxe_IMap = function() { };
haxe_IMap.__name__ = ["haxe","IMap"];
haxe_IMap.prototype = {
	__class__: haxe_IMap
};
var haxe_ds_Option = { __ename__ : ["haxe","ds","Option"], __constructs__ : ["Some","None"] };
haxe_ds_Option.Some = function(v) { var $x = ["Some",0,v]; $x.__enum__ = haxe_ds_Option; $x.toString = $estr; return $x; };
haxe_ds_Option.None = ["None",1];
haxe_ds_Option.None.toString = $estr;
haxe_ds_Option.None.__enum__ = haxe_ds_Option;
var haxe_ds_StringMap = function() {
	this.h = { };
};
haxe_ds_StringMap.__name__ = ["haxe","ds","StringMap"];
haxe_ds_StringMap.__interfaces__ = [haxe_IMap];
haxe_ds_StringMap.prototype = {
	set: function(key,value) {
		if(__map_reserved[key] != null) this.setReserved(key,value); else this.h[key] = value;
	}
	,get: function(key) {
		if(__map_reserved[key] != null) return this.getReserved(key);
		return this.h[key];
	}
	,exists: function(key) {
		if(__map_reserved[key] != null) return this.existsReserved(key);
		return this.h.hasOwnProperty(key);
	}
	,setReserved: function(key,value) {
		if(this.rh == null) this.rh = { };
		this.rh["$" + key] = value;
	}
	,getReserved: function(key) {
		if(this.rh == null) return null; else return this.rh["$" + key];
	}
	,existsReserved: function(key) {
		if(this.rh == null) return false;
		return this.rh.hasOwnProperty("$" + key);
	}
	,remove: function(key) {
		if(__map_reserved[key] != null) {
			key = "$" + key;
			if(this.rh == null || !this.rh.hasOwnProperty(key)) return false;
			delete(this.rh[key]);
			return true;
		} else {
			if(!this.h.hasOwnProperty(key)) return false;
			delete(this.h[key]);
			return true;
		}
	}
	,keys: function() {
		return HxOverrides.iter(this.arrayKeys());
	}
	,arrayKeys: function() {
		var out = [];
		for( var key in this.h ) {
		if(this.h.hasOwnProperty(key)) out.push(key);
		}
		if(this.rh != null) {
			for( var key in this.rh ) {
			if(key.charCodeAt(0) == 36) out.push(key.substr(1));
			}
		}
		return out;
	}
	,__class__: haxe_ds_StringMap
};
var js__$Boot_HaxeError = function(val) {
	Error.call(this);
	this.val = val;
	this.message = String(val);
	if(Error.captureStackTrace) Error.captureStackTrace(this,js__$Boot_HaxeError);
};
js__$Boot_HaxeError.__name__ = ["js","_Boot","HaxeError"];
js__$Boot_HaxeError.__super__ = Error;
js__$Boot_HaxeError.prototype = $extend(Error.prototype,{
	__class__: js__$Boot_HaxeError
});
var js_Boot = function() { };
js_Boot.__name__ = ["js","Boot"];
js_Boot.getClass = function(o) {
	if((o instanceof Array) && o.__enum__ == null) return Array; else {
		var cl = o.__class__;
		if(cl != null) return cl;
		var name = js_Boot.__nativeClassName(o);
		if(name != null) return js_Boot.__resolveNativeClass(name);
		return null;
	}
};
js_Boot.__string_rec = function(o,s) {
	if(o == null) return "null";
	if(s.length >= 5) return "<...>";
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) t = "object";
	switch(t) {
	case "object":
		if(o instanceof Array) {
			if(o.__enum__) {
				if(o.length == 2) return o[0];
				var str2 = o[0] + "(";
				s += "\t";
				var _g1 = 2;
				var _g = o.length;
				while(_g1 < _g) {
					var i1 = _g1++;
					if(i1 != 2) str2 += "," + js_Boot.__string_rec(o[i1],s); else str2 += js_Boot.__string_rec(o[i1],s);
				}
				return str2 + ")";
			}
			var l = o.length;
			var i;
			var str1 = "[";
			s += "\t";
			var _g2 = 0;
			while(_g2 < l) {
				var i2 = _g2++;
				str1 += (i2 > 0?",":"") + js_Boot.__string_rec(o[i2],s);
			}
			str1 += "]";
			return str1;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e ) {
			haxe_CallStack.lastException = e;
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") return s2;
		}
		var k = null;
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		for( var k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) str += ", \n";
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "function":
		return "<function>";
	case "string":
		return o;
	default:
		return String(o);
	}
};
js_Boot.__interfLoop = function(cc,cl) {
	if(cc == null) return false;
	if(cc == cl) return true;
	var intf = cc.__interfaces__;
	if(intf != null) {
		var _g1 = 0;
		var _g = intf.length;
		while(_g1 < _g) {
			var i = _g1++;
			var i1 = intf[i];
			if(i1 == cl || js_Boot.__interfLoop(i1,cl)) return true;
		}
	}
	return js_Boot.__interfLoop(cc.__super__,cl);
};
js_Boot.__instanceof = function(o,cl) {
	if(cl == null) return false;
	switch(cl) {
	case Int:
		return (o|0) === o;
	case Float:
		return typeof(o) == "number";
	case Bool:
		return typeof(o) == "boolean";
	case String:
		return typeof(o) == "string";
	case Array:
		return (o instanceof Array) && o.__enum__ == null;
	case Dynamic:
		return true;
	default:
		if(o != null) {
			if(typeof(cl) == "function") {
				if(o instanceof cl) return true;
				if(js_Boot.__interfLoop(js_Boot.getClass(o),cl)) return true;
			} else if(typeof(cl) == "object" && js_Boot.__isNativeObj(cl)) {
				if(o instanceof cl) return true;
			}
		} else return false;
		if(cl == Class && o.__name__ != null) return true;
		if(cl == Enum && o.__ename__ != null) return true;
		return o.__enum__ == cl;
	}
};
js_Boot.__nativeClassName = function(o) {
	var name = js_Boot.__toStr.call(o).slice(8,-1);
	if(name == "Object" || name == "Function" || name == "Math" || name == "JSON") return null;
	return name;
};
js_Boot.__isNativeObj = function(o) {
	return js_Boot.__nativeClassName(o) != null;
};
js_Boot.__resolveNativeClass = function(name) {
	return $global[name];
};
var js_html_compat_ArrayBuffer = function(a) {
	if((a instanceof Array) && a.__enum__ == null) {
		this.a = a;
		this.byteLength = a.length;
	} else {
		var len = a;
		this.a = [];
		var _g = 0;
		while(_g < len) {
			var i = _g++;
			this.a[i] = 0;
		}
		this.byteLength = len;
	}
};
js_html_compat_ArrayBuffer.__name__ = ["js","html","compat","ArrayBuffer"];
js_html_compat_ArrayBuffer.sliceImpl = function(begin,end) {
	var u = new Uint8Array(this,begin,end == null?null:end - begin);
	var result = new ArrayBuffer(u.byteLength);
	var resultArray = new Uint8Array(result);
	resultArray.set(u);
	return result;
};
js_html_compat_ArrayBuffer.prototype = {
	slice: function(begin,end) {
		return new js_html_compat_ArrayBuffer(this.a.slice(begin,end));
	}
	,__class__: js_html_compat_ArrayBuffer
};
var js_html_compat_Uint8Array = function() { };
js_html_compat_Uint8Array.__name__ = ["js","html","compat","Uint8Array"];
js_html_compat_Uint8Array._new = function(arg1,offset,length) {
	var arr;
	if(typeof(arg1) == "number") {
		arr = [];
		var _g = 0;
		while(_g < arg1) {
			var i = _g++;
			arr[i] = 0;
		}
		arr.byteLength = arr.length;
		arr.byteOffset = 0;
		arr.buffer = new js_html_compat_ArrayBuffer(arr);
	} else if(js_Boot.__instanceof(arg1,js_html_compat_ArrayBuffer)) {
		var buffer = arg1;
		if(offset == null) offset = 0;
		if(length == null) length = buffer.byteLength - offset;
		if(offset == 0) arr = buffer.a; else arr = buffer.a.slice(offset,offset + length);
		arr.byteLength = arr.length;
		arr.byteOffset = offset;
		arr.buffer = buffer;
	} else if((arg1 instanceof Array) && arg1.__enum__ == null) {
		arr = arg1.slice();
		arr.byteLength = arr.length;
		arr.byteOffset = 0;
		arr.buffer = new js_html_compat_ArrayBuffer(arr);
	} else throw new js__$Boot_HaxeError("TODO " + Std.string(arg1));
	arr.subarray = js_html_compat_Uint8Array._subarray;
	arr.set = js_html_compat_Uint8Array._set;
	return arr;
};
js_html_compat_Uint8Array._set = function(arg,offset) {
	var t = this;
	if((function($this) {
		var $r;
		var v = arg.buffer;
		$r = js_Boot.__instanceof(v,js_html_compat_ArrayBuffer);
		return $r;
	}(this))) {
		var a = arg;
		if(arg.byteLength + offset > t.byteLength) throw new js__$Boot_HaxeError("set() outside of range");
		var _g1 = 0;
		var _g = arg.byteLength;
		while(_g1 < _g) {
			var i = _g1++;
			t[i + offset] = a[i];
		}
	} else if((arg instanceof Array) && arg.__enum__ == null) {
		var a1 = arg;
		if(a1.length + offset > t.byteLength) throw new js__$Boot_HaxeError("set() outside of range");
		var _g11 = 0;
		var _g2 = a1.length;
		while(_g11 < _g2) {
			var i1 = _g11++;
			t[i1 + offset] = a1[i1];
		}
	} else throw new js__$Boot_HaxeError("TODO");
};
js_html_compat_Uint8Array._subarray = function(start,end) {
	var t = this;
	var a = js_html_compat_Uint8Array._new(t.slice(start,end));
	a.byteOffset = start;
	return a;
};
var lies_Store = function(reducer,initialState) {
	this.state = initialState;
	this.reducer = reducer;
	this.listeners = [];
};
lies_Store.__name__ = ["lies","Store"];
lies_Store.create = function(reducer,initialState) {
	return new lies_Store(reducer,initialState);
};
lies_Store.prototype = {
	dispatch: function(action) {
		if(null == action) throw new thx_Error("cannot dispatch a null action",null,{ fileName : "Store.hx", lineNumber : 20, className : "lies.Store", methodName : "dispatch"});
		var oldState = this.state;
		var value = this.reducer(oldState,action);
		this.state = value._0;
		this.invokeListeners(this.state,oldState,action);
		var _g = 0;
		var _g1 = value._1;
		while(_g < _g1.length) {
			var future = _g1[_g];
			++_g;
			future.then($bind(this,this.dispatch));
		}
	}
	,invokeListeners: function(currentState,oldState,action) {
		var _g = 0;
		var _g1 = this.listeners.slice();
		while(_g < _g1.length) {
			var listener = _g1[_g];
			++_g;
			listener(currentState,oldState,action);
		}
	}
	,subscribe: function(listener) {
		var _g = this;
		HxOverrides.remove(this.listeners,listener);
		this.listeners.push(listener);
		return function() {
			HxOverrides.remove(_g.listeners,listener);
		};
	}
	,__class__: lies_Store
};
var thx_Arrays = function() { };
thx_Arrays.__name__ = ["thx","Arrays"];
thx_Arrays.all = function(arr,predicate) {
	var tmp = HxOverrides.iter(arr);
	while(tmp.hasNext()) {
		var element = tmp.next();
		if(!predicate(element)) return false;
	}
	return true;
};
thx_Arrays.findIndex = function(array,predicate) {
	var _g1 = 0;
	var _g = array.length;
	while(_g1 < _g) {
		var i = _g1++;
		if(predicate(array[i])) return i;
	}
	return -1;
};
thx_Arrays.string = function(arr) {
	return "[" + arr.map(thx_Dynamics.string).join(", ") + "]";
};
var thx_Dynamics = function() { };
thx_Dynamics.__name__ = ["thx","Dynamics"];
thx_Dynamics.string = function(v) {
	var _g = Type["typeof"](v);
	switch(_g[1]) {
	case 0:
		return "null";
	case 1:case 2:case 3:
		return "" + Std.string(v);
	case 4:
		return thx_Objects.string(v);
	case 6:
		var c = _g[2];
		var _g1 = Type.getClassName(c);
		switch(_g1) {
		case "Array":
			return thx_Arrays.string(v);
		case "String":
			return v;
		case "Date":
			return HxOverrides.dateStr(v);
		default:
			if(js_Boot.__instanceof(v,haxe_IMap)) return thx_Maps.string(v); else return Std.string(v);
		}
		break;
	case 7:
		return thx_Enums.string(v);
	case 8:
		return "<unknown>";
	case 5:
		return "<function>";
	}
};
var thx_Either = { __ename__ : ["thx","Either"], __constructs__ : ["Left","Right"] };
thx_Either.Left = function(value) { var $x = ["Left",0,value]; $x.__enum__ = thx_Either; $x.toString = $estr; return $x; };
thx_Either.Right = function(value) { var $x = ["Right",1,value]; $x.__enum__ = thx_Either; $x.toString = $estr; return $x; };
var thx_Enums = function() { };
thx_Enums.__name__ = ["thx","Enums"];
thx_Enums.string = function(e) {
	var cons = e[0];
	var params = [];
	var _g = 0;
	var _g1 = e.slice(2);
	while(_g < _g1.length) {
		var param = _g1[_g];
		++_g;
		params.push(thx_Dynamics.string(param));
	}
	return cons + (params.length == 0?"":"(" + params.join(", ") + ")");
};
var thx_Error = function(message,stack,pos) {
	Error.call(this,message);
	this.message = message;
	if(null == stack) {
		try {
			stack = haxe_CallStack.exceptionStack();
		} catch( e ) {
			haxe_CallStack.lastException = e;
			stack = [];
		}
		if(stack.length == 0) try {
			stack = haxe_CallStack.callStack();
		} catch( e1 ) {
			haxe_CallStack.lastException = e1;
			stack = [];
		}
	}
	this.stackItems = stack;
	this.pos = pos;
};
thx_Error.__name__ = ["thx","Error"];
thx_Error.__super__ = Error;
thx_Error.prototype = $extend(Error.prototype,{
	toString: function() {
		return this.message + "\nfrom: " + this.getPosition() + "\n\n" + this.stackToString();
	}
	,getPosition: function() {
		return this.pos.className + "." + this.pos.methodName + "() at " + this.pos.lineNumber;
	}
	,stackToString: function() {
		return haxe_CallStack.toString(this.stackItems);
	}
	,__class__: thx_Error
});
var thx_Iterators = function() { };
thx_Iterators.__name__ = ["thx","Iterators"];
thx_Iterators.map = function(it,f) {
	var acc = [];
	while(it.hasNext()) {
		var v = it.next();
		acc.push(f(v));
	}
	return acc;
};
thx_Iterators.toArray = function(it) {
	var elements = [];
	while(it.hasNext()) {
		var element = it.next();
		elements.push(element);
	}
	return elements;
};
var thx_Maps = function() { };
thx_Maps.__name__ = ["thx","Maps"];
thx_Maps.tuples = function(map) {
	return thx_Iterators.map(map.keys(),function(key) {
		return { _0 : key, _1 : map.get(key)};
	});
};
thx_Maps.string = function(m) {
	return "[" + thx_Maps.tuples(m).map(function(t) {
		return thx_Dynamics.string(t._0) + " => " + thx_Dynamics.string(t._1);
	}).join(", ") + "]";
};
var thx_Objects = function() { };
thx_Objects.__name__ = ["thx","Objects"];
thx_Objects.combine = function(first,second) {
	var to = { };
	var _g = 0;
	var _g1 = Reflect.fields(first);
	while(_g < _g1.length) {
		var field = _g1[_g];
		++_g;
		to[field] = Reflect.field(first,field);
	}
	var _g2 = 0;
	var _g11 = Reflect.fields(second);
	while(_g2 < _g11.length) {
		var field1 = _g11[_g2];
		++_g2;
		to[field1] = Reflect.field(second,field1);
	}
	return to;
};
thx_Objects.string = function(o) {
	return "{" + Reflect.fields(o).map(function(key) {
		var v = Reflect.field(o,key);
		var s = typeof(v) == "string"?thx_Strings.quote(v):thx_Dynamics.string(v);
		return "" + key + " : " + s;
	}).join(", ") + "}";
};
var thx__$Set_Set_$Impl_$ = {};
thx__$Set_Set_$Impl_$.__name__ = ["thx","_Set","Set_Impl_"];
thx__$Set_Set_$Impl_$.createString = function(it) {
	var map = new haxe_ds_StringMap();
	var set = map;
	if(null != it) thx__$Set_Set_$Impl_$.pushMany(set,it);
	return set;
};
thx__$Set_Set_$Impl_$.add = function(this1,v) {
	if(this1.exists(v)) return false; else {
		this1.set(v,true);
		return true;
	}
};
thx__$Set_Set_$Impl_$.copy = function(this1) {
	var inst = thx__$Set_Set_$Impl_$.empty(this1);
	var tmp = this1.keys();
	while(tmp.hasNext()) {
		var k = tmp.next();
		inst.set(k,true);
	}
	return inst;
};
thx__$Set_Set_$Impl_$.empty = function(this1) {
	var inst = Type.createInstance(this1 == null?null:js_Boot.getClass(this1),[]);
	return inst;
};
thx__$Set_Set_$Impl_$.filter = function(this1,predicate) {
	var tmp = thx__$Set_Set_$Impl_$.empty(this1);
	return thx__$Set_Set_$Impl_$.reduce(this1,function(acc,v) {
		if(predicate(v)) thx__$Set_Set_$Impl_$.add(acc,v);
		return acc;
	},tmp);
};
thx__$Set_Set_$Impl_$.map = function(this1,f) {
	return thx__$Set_Set_$Impl_$.reduce(this1,function(acc,v) {
		acc.push(f(v));
		return acc;
	},[]);
};
thx__$Set_Set_$Impl_$.pushMany = function(this1,values) {
	var tmp = $iterator(values)();
	while(tmp.hasNext()) {
		var value = tmp.next();
		this1.set(value,true);
	}
};
thx__$Set_Set_$Impl_$.reduce = function(this1,handler,acc) {
	var tmp = $iterator(thx__$Set_Set_$Impl_$)(this1);
	while(tmp.hasNext()) {
		var v = tmp.next();
		acc = handler(acc,v);
	}
	return acc;
};
thx__$Set_Set_$Impl_$.iterator = function(this1) {
	return this1.keys();
};
var thx_Strings = function() { };
thx_Strings.__name__ = ["thx","Strings"];
thx_Strings.ellipsis = function(s,maxlen,symbol) {
	if(symbol == null) symbol = "…";
	if(maxlen == null) maxlen = 20;
	var sl = s.length;
	var symboll = symbol.length;
	if(sl > maxlen) {
		if(maxlen < symboll) return HxOverrides.substr(symbol,symboll - maxlen,maxlen); else return HxOverrides.substr(s,0,maxlen - symboll) + symbol;
	} else return s;
};
thx_Strings.ellipsisMiddle = function(s,maxlen,symbol) {
	if(symbol == null) symbol = "…";
	if(maxlen == null) maxlen = 20;
	var sl = s.length;
	var symboll = symbol.length;
	if(sl > maxlen) {
		if(maxlen <= symboll) return thx_Strings.ellipsis(s,maxlen,symbol);
		var hll = Math.ceil((maxlen - symboll) / 2);
		var hlr = Math.floor((maxlen - symboll) / 2);
		return HxOverrides.substr(s,0,hll) + symbol + HxOverrides.substr(s,sl - hlr,hlr);
	} else return s;
};
thx_Strings.isEmpty = function(value) {
	if(!(value == null)) return value == ""; else return true;
};
thx_Strings.quote = function(s) {
	if(s.indexOf("\"") < 0) return "\"" + s + "\""; else if(s.indexOf("'") < 0) return "'" + s + "'"; else return "\"" + StringTools.replace(s,"\"","\\\"") + "\"";
};
thx_Strings.trimCharsLeft = function(value,charlist) {
	var pos = 0;
	var _g1 = 0;
	var _g = value.length;
	while(_g1 < _g) {
		var i = _g1++;
		if(charlist.indexOf(value.charAt(i)) >= 0) ++pos; else break;
	}
	return value.substring(pos);
};
var thx_Timer = function() { };
thx_Timer.__name__ = ["thx","Timer"];
thx_Timer.immediate = function(callback) {
	return (function($this) {
		var $r;
		var id = setImmediate(callback);
		$r = function() {
			thx_Timer.clear(id);
		};
		return $r;
	}(this));
};
thx_Timer.clear = function(id) {
	clearTimeout(id);
	return;
};
var thx_Types = function() { };
thx_Types.__name__ = ["thx","Types"];
thx_Types.sameType = function(a,b) {
	return thx_Types.toString(Type["typeof"](a)) == thx_Types.toString(Type["typeof"](b));
};
thx_Types.toString = function(type) {
	switch(type[1]) {
	case 0:
		return "Null";
	case 1:
		return "Int";
	case 2:
		return "Float";
	case 3:
		return "Bool";
	case 4:
		return "{}";
	case 5:
		return "Function";
	case 6:
		var c = type[2];
		return Type.getClassName(c);
	case 7:
		var e = type[2];
		return Type.getEnumName(e);
	default:
		throw new js__$Boot_HaxeError("invalid type " + Std.string(type));
	}
};
var thx_Uuid = function() { };
thx_Uuid.__name__ = ["thx","Uuid"];
thx_Uuid.create = function() {
	var s = [];
	var _g = 0;
	while(_g < 8) {
		var i = _g++;
		s[i] = "0123456789ABCDEF".charAt(Math.floor(Math.random() * 16));
	}
	s[8] = "-";
	var _g1 = 9;
	while(_g1 < 13) {
		var i1 = _g1++;
		s[i1] = "0123456789ABCDEF".charAt(Math.floor(Math.random() * 16));
	}
	s[13] = "-";
	s[14] = "4";
	var _g2 = 15;
	while(_g2 < 18) {
		var i2 = _g2++;
		s[i2] = "0123456789ABCDEF".charAt(Math.floor(Math.random() * 16));
	}
	s[18] = "-";
	s[19] = "89AB".charAt(Math.floor(Math.random() * 16) & 3);
	var _g3 = 20;
	while(_g3 < 23) {
		var i3 = _g3++;
		s[i3] = "0123456789ABCDEF".charAt(Math.floor(Math.random() * 16));
	}
	s[23] = "-";
	var _g4 = 24;
	while(_g4 < 36) {
		var i4 = _g4++;
		s[i4] = "0123456789ABCDEF".charAt(Math.floor(Math.random() * 16));
	}
	return s.join("");
};
var thx_error_AbstractMethod = function(posInfo) {
	thx_Error.call(this,"method " + posInfo.className + "." + posInfo.methodName + "() is abstract",null,posInfo);
};
thx_error_AbstractMethod.__name__ = ["thx","error","AbstractMethod"];
thx_error_AbstractMethod.__super__ = thx_Error;
thx_error_AbstractMethod.prototype = $extend(thx_Error.prototype,{
	__class__: thx_error_AbstractMethod
});
var thx_promise_Future = function() { };
thx_promise_Future.__name__ = ["thx","promise","Future"];
thx_promise_Future.prototype = {
	then: function(handler) {
		this.handlers.push(handler);
		this.update();
		return this;
	}
	,update: function() {
		var _g = this.state;
		switch(_g[1]) {
		case 1:
			break;
		case 0:
			var result = _g[2];
			var index = -1;
			while(true) {
				++index;
				if(!(index < this.handlers.length)) break;
				this.handlers[index](result);
			}
			this.handlers = [];
			break;
		}
	}
	,__class__: thx_promise_Future
};
var todomvc_data_Reducers = function() { };
todomvc_data_Reducers.__name__ = ["todomvc","data","Reducers"];
todomvc_data_Reducers.todoApp = function(state,action) {
	return { visibilityFilter : todomvc_data_Reducers.visibilityFilter(state.visibilityFilter,action), todos : todomvc_data_Reducers.todos(state.todos,action)};
};
todomvc_data_Reducers.todos = function(state,action) {
	switch(action[1]) {
	case 0:
		var text = action[2];
		return state.concat([{ id : thx_Uuid.create(), text : text, completed : false}]);
	case 1:
		var id = action[2];
		var index = todomvc_data_Reducers.getIndex(state,id);
		return state.slice(0,index).concat([thx_Objects.combine(state[index],{ completed : !state[index].completed})]).concat(state.slice(index + 1));
	case 2:
		var id1 = action[2];
		var index1 = todomvc_data_Reducers.getIndex(state,id1);
		return state.slice(0,index1).concat(state.slice(index1 + 1));
	case 4:
		var text1 = action[3];
		var id2 = action[2];
		var index2 = todomvc_data_Reducers.getIndex(state,id2);
		return state.slice(0,index2).concat([thx_Objects.combine(state[index2],{ text : text1})]).concat(state.slice(index2 + 1));
	case 5:
		return state.filter(function(_) {
			return !_.completed;
		});
	case 6:
		var _e = state;
		var completed = !(function(predicate) {
			return thx_Arrays.all(_e,predicate);
		})(function(_1) {
			return _1.completed;
		});
		return state.map(function(_2) {
			return { id : _2.id, text : _2.text, completed : completed};
		});
	default:
		return state;
	}
};
todomvc_data_Reducers.getIndex = function(items,id) {
	return thx_Arrays.findIndex(items,function(item) {
		return item.id == id;
	});
};
todomvc_data_Reducers.visibilityFilter = function(state,action) {
	switch(action[1]) {
	case 3:
		var filter = action[2];
		return filter;
	default:
		return state;
	}
};
var todomvc_data_TodoAction = { __ename__ : ["todomvc","data","TodoAction"], __constructs__ : ["Add","Toggle","Remove","SetVisibilityFilter","UpdateText","ClearCompleted","ToggleAll"] };
todomvc_data_TodoAction.Add = function(text) { var $x = ["Add",0,text]; $x.__enum__ = todomvc_data_TodoAction; $x.toString = $estr; return $x; };
todomvc_data_TodoAction.Toggle = function(id) { var $x = ["Toggle",1,id]; $x.__enum__ = todomvc_data_TodoAction; $x.toString = $estr; return $x; };
todomvc_data_TodoAction.Remove = function(id) { var $x = ["Remove",2,id]; $x.__enum__ = todomvc_data_TodoAction; $x.toString = $estr; return $x; };
todomvc_data_TodoAction.SetVisibilityFilter = function(filter) { var $x = ["SetVisibilityFilter",3,filter]; $x.__enum__ = todomvc_data_TodoAction; $x.toString = $estr; return $x; };
todomvc_data_TodoAction.UpdateText = function(id,text) { var $x = ["UpdateText",4,id,text]; $x.__enum__ = todomvc_data_TodoAction; $x.toString = $estr; return $x; };
todomvc_data_TodoAction.ClearCompleted = ["ClearCompleted",5];
todomvc_data_TodoAction.ClearCompleted.toString = $estr;
todomvc_data_TodoAction.ClearCompleted.__enum__ = todomvc_data_TodoAction;
todomvc_data_TodoAction.ToggleAll = ["ToggleAll",6];
todomvc_data_TodoAction.ToggleAll.toString = $estr;
todomvc_data_TodoAction.ToggleAll.__enum__ = todomvc_data_TodoAction;
var todomvc_data_VisibilityFilter = { __ename__ : ["todomvc","data","VisibilityFilter"], __constructs__ : ["ShowAll","ShowCompleted","ShowActive"] };
todomvc_data_VisibilityFilter.ShowAll = ["ShowAll",0];
todomvc_data_VisibilityFilter.ShowAll.toString = $estr;
todomvc_data_VisibilityFilter.ShowAll.__enum__ = todomvc_data_VisibilityFilter;
todomvc_data_VisibilityFilter.ShowCompleted = ["ShowCompleted",1];
todomvc_data_VisibilityFilter.ShowCompleted.toString = $estr;
todomvc_data_VisibilityFilter.ShowCompleted.__enum__ = todomvc_data_VisibilityFilter;
todomvc_data_VisibilityFilter.ShowActive = ["ShowActive",2];
todomvc_data_VisibilityFilter.ShowActive.toString = $estr;
todomvc_data_VisibilityFilter.ShowActive.__enum__ = todomvc_data_VisibilityFilter;
var todomvc_data_VisibilityFilters = function() { };
todomvc_data_VisibilityFilters.__name__ = ["todomvc","data","VisibilityFilters"];
todomvc_data_VisibilityFilters.filterVisibility = function(arr,filter) {
	switch(filter[1]) {
	case 0:
		return arr.slice();
	case 2:
		return arr.filter(function(_) {
			return !_.completed;
		});
	case 1:
		return arr.filter(function(_1) {
			return _1.completed;
		});
	}
};
var todomvc_view_App = function(api,state,children) {
	doom_Component.call(this,api,state,children);
};
todomvc_view_App.__name__ = ["todomvc","view","App"];
todomvc_view_App.__super__ = doom_Component;
todomvc_view_App.prototype = $extend(doom_Component.prototype,{
	render: function() {
		var _g = this;
		var header = new todomvc_view_Header({ add : function(text) {
			_g.api.dispatch(todomvc_data_TodoAction.Add(text));
		}},{ });
		var body = new todomvc_view_Body({ setFilter : function(filter) {
			_g.api.dispatch(todomvc_data_TodoAction.SetVisibilityFilter(filter));
		}, clearCompleted : function() {
			_g.api.dispatch(todomvc_data_TodoAction.ClearCompleted);
		}, remove : function(id) {
			_g.api.dispatch(todomvc_data_TodoAction.Remove(id));
		}, toggle : function(id1) {
			_g.api.dispatch(todomvc_data_TodoAction.Toggle(id1));
		}, toggleAll : function() {
			_g.api.dispatch(todomvc_data_TodoAction.ToggleAll);
		}, updateText : function(id2,text1) {
			_g.api.dispatch(todomvc_data_TodoAction.UpdateText(id2,text1));
		}},this.api.state);
		var f = function() {
			body.update(_g.api.state);
		};
		this.api.subscribe(function(_,_1,_2) {
			f();
		});
		return doom__$Node_Node_$Impl_$.el("div",null,[doom_NodeImpl.ComponentNode(header),doom_NodeImpl.ComponentNode(body)],null);
	}
	,__class__: todomvc_view_App
});
var todomvc_view_Body = function(api,state,children) {
	doom_Component.call(this,api,state,children);
};
todomvc_view_Body.__name__ = ["todomvc","view","Body"];
todomvc_view_Body.__super__ = doom_Component;
todomvc_view_Body.prototype = $extend(doom_Component.prototype,{
	render: function() {
		if(this.state.todos.length == 0) {
			var _g = new haxe_ds_StringMap();
			var value = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("display:none");
			if(__map_reserved.style != null) _g.setReserved("style",value); else _g.h["style"] = value;
			var value1 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("nothing to do yet");
			if(__map_reserved["data-comment"] != null) _g.setReserved("data-comment",value1); else _g.h["data-comment"] = value1;
			return doom__$Node_Node_$Impl_$.el("div",_g);
		} else {
			var all = this.state.todos.length;
			var completed = todomvc_data_VisibilityFilters.filterVisibility(this.state.todos,todomvc_data_VisibilityFilter.ShowCompleted).length;
			var remaining = all - completed;
			return doom__$Node_Node_$Impl_$.el("div",null,[doom_NodeImpl.ComponentNode(new todomvc_view_List(this.api,{ items : todomvc_data_VisibilityFilters.filterVisibility(this.state.todos,this.state.visibilityFilter), allCompleted : completed == 0})),doom_NodeImpl.ComponentNode(new todomvc_view_Footer(this.api,{ remaining : remaining, filter : this.state.visibilityFilter, hasCompleted : completed > 0}))],null);
		}
	}
	,__class__: todomvc_view_Body
});
var todomvc_view_Footer = function(api,state,children) {
	doom_Component.call(this,api,state,children);
};
todomvc_view_Footer.__name__ = ["todomvc","view","Footer"];
todomvc_view_Footer.__super__ = doom_Component;
todomvc_view_Footer.prototype = $extend(doom_Component.prototype,{
	render: function() {
		var _g = new haxe_ds_StringMap();
		var value = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("todo-count");
		if(__map_reserved["class"] != null) _g.setReserved("class",value); else _g.h["class"] = value;
		var tmp = doom__$Node_Node_$Impl_$.el("span",_g,this.getItemsLeftLabel(),null);
		var _g1 = new haxe_ds_StringMap();
		var value1 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("filters");
		if(__map_reserved["class"] != null) _g1.setReserved("class",value1); else _g1.h["class"] = value1;
		var _g7 = new haxe_ds_StringMap();
		var _g6 = new haxe_ds_StringMap();
		var value3 = this.isFilter(todomvc_data_VisibilityFilter.ShowAll);
		if(__map_reserved.selected != null) _g6.setReserved("selected",value3); else _g6.h["selected"] = value3;
		var value2 = doom__$AttributeValue_AttributeValue_$Impl_$.fromMap(_g6);
		if(__map_reserved["class"] != null) _g7.setReserved("class",value2); else _g7.h["class"] = value2;
		var value4 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("#");
		if(__map_reserved.href != null) _g7.setReserved("href",value4); else _g7.h["href"] = value4;
		var f = $bind(this,this.handleClickFilter);
		var value5 = doom__$AttributeValue_AttributeValue_$Impl_$.fromHandler(function() {
			f(todomvc_data_VisibilityFilter.ShowAll);
		});
		if(__map_reserved.click != null) _g7.setReserved("click",value5); else _g7.h["click"] = value5;
		var tmp1 = doom__$Node_Node_$Impl_$.el("li",null,null,doom__$Node_Node_$Impl_$.el("a",_g7,null,doom_NodeImpl.Text("All")));
		var _g13 = new haxe_ds_StringMap();
		var _g12 = new haxe_ds_StringMap();
		var value7 = this.isFilter(todomvc_data_VisibilityFilter.ShowActive);
		if(__map_reserved.selected != null) _g12.setReserved("selected",value7); else _g12.h["selected"] = value7;
		var value6 = doom__$AttributeValue_AttributeValue_$Impl_$.fromMap(_g12);
		if(__map_reserved["class"] != null) _g13.setReserved("class",value6); else _g13.h["class"] = value6;
		var value8 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("#/active");
		if(__map_reserved.href != null) _g13.setReserved("href",value8); else _g13.h["href"] = value8;
		var f1 = $bind(this,this.handleClickFilter);
		var value9 = doom__$AttributeValue_AttributeValue_$Impl_$.fromHandler(function() {
			f1(todomvc_data_VisibilityFilter.ShowActive);
		});
		if(__map_reserved.click != null) _g13.setReserved("click",value9); else _g13.h["click"] = value9;
		var tmp2 = doom__$Node_Node_$Impl_$.el("li",null,null,doom__$Node_Node_$Impl_$.el("a",_g13,null,doom_NodeImpl.Text("Active")));
		var _g19 = new haxe_ds_StringMap();
		var _g18 = new haxe_ds_StringMap();
		var value11 = this.isFilter(todomvc_data_VisibilityFilter.ShowCompleted);
		if(__map_reserved.selected != null) _g18.setReserved("selected",value11); else _g18.h["selected"] = value11;
		var value10 = doom__$AttributeValue_AttributeValue_$Impl_$.fromMap(_g18);
		if(__map_reserved["class"] != null) _g19.setReserved("class",value10); else _g19.h["class"] = value10;
		var value12 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("#/completed");
		if(__map_reserved.href != null) _g19.setReserved("href",value12); else _g19.h["href"] = value12;
		var f2 = $bind(this,this.handleClickFilter);
		var value13 = doom__$AttributeValue_AttributeValue_$Impl_$.fromHandler(function() {
			f2(todomvc_data_VisibilityFilter.ShowCompleted);
		});
		if(__map_reserved.click != null) _g19.setReserved("click",value13); else _g19.h["click"] = value13;
		var footerContent = [tmp,doom__$Node_Node_$Impl_$.el("ul",_g1,[tmp1,tmp2,doom__$Node_Node_$Impl_$.el("li",null,null,doom__$Node_Node_$Impl_$.el("a",_g19,null,doom_NodeImpl.Text("Completed")))],null)];
		if(this.state.hasCompleted) {
			var _g201 = new haxe_ds_StringMap();
			var value14 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("clear-completed");
			if(__map_reserved["class"] != null) _g201.setReserved("class",value14); else _g201.h["class"] = value14;
			var value15 = doom__$AttributeValue_AttributeValue_$Impl_$.fromHandler($bind(this,this.handleClear));
			if(__map_reserved.click != null) _g201.setReserved("click",value15); else _g201.h["click"] = value15;
			footerContent.push(doom__$Node_Node_$Impl_$.el("button",_g201,null,doom_NodeImpl.Text("Clear completed")));
		}
		var _g20 = new haxe_ds_StringMap();
		var value16 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("footer");
		if(__map_reserved["class"] != null) _g20.setReserved("class",value16); else _g20.h["class"] = value16;
		return doom__$Node_Node_$Impl_$.el("footer",_g20,footerContent,null);
	}
	,handleClear: function() {
		this.api.clearCompleted();
	}
	,handleClickFilter: function(filter) {
		this.api.setFilter(filter);
	}
	,isFilter: function(filter) {
		return Type.enumEq(this.state.filter,filter);
	}
	,getItemsLeftLabel: function() {
		if(this.state.remaining == 1) return [doom__$Node_Node_$Impl_$.el("strong",null,null,doom_NodeImpl.Text("1")),doom_NodeImpl.Text(" item left")]; else return [doom__$Node_Node_$Impl_$.el("strong",null,null,doom_NodeImpl.Text("" + this.state.remaining)),doom_NodeImpl.Text(" items left")];
	}
	,__class__: todomvc_view_Footer
});
var todomvc_view_Header = function(api,state,children) {
	doom_Component.call(this,api,state,children);
};
todomvc_view_Header.__name__ = ["todomvc","view","Header"];
todomvc_view_Header.__super__ = doom_Component;
todomvc_view_Header.prototype = $extend(doom_Component.prototype,{
	render: function() {
		var _g = new haxe_ds_StringMap();
		var value = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("header");
		if(__map_reserved["class"] != null) _g.setReserved("class",value); else _g.h["class"] = value;
		var tmp = doom__$Node_Node_$Impl_$.el("h1",null,null,doom_NodeImpl.Text("todos"));
		var _g1 = new haxe_ds_StringMap();
		var value1 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("new-todo");
		if(__map_reserved["class"] != null) _g1.setReserved("class",value1); else _g1.h["class"] = value1;
		var value2 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("What needs to be done?");
		if(__map_reserved.placeholder != null) _g1.setReserved("placeholder",value2); else _g1.h["placeholder"] = value2;
		var value3 = doom__$AttributeValue_AttributeValue_$Impl_$.fromBool(true);
		if(__map_reserved.autofocus != null) _g1.setReserved("autofocus",value3); else _g1.h["autofocus"] = value3;
		var value4 = doom__$AttributeValue_AttributeValue_$Impl_$.fromEventHandler($bind(this,this.handleKeys));
		if(__map_reserved.keydown != null) _g1.setReserved("keydown",value4); else _g1.h["keydown"] = value4;
		return doom__$Node_Node_$Impl_$.el("header",_g,[tmp,doom__$Node_Node_$Impl_$.el("input",_g1,null,null)],null);
	}
	,handleKeys: function(e) {
		if(13 == e.which) {
			e.preventDefault();
			var value = this.getInputValueAndEmpty();
			if(thx_Strings.isEmpty(value)) return;
			this.api.add(value);
		}
	}
	,getInputValueAndEmpty: function() {
		var el = this.element.querySelector("input");
		var value = StringTools.trim(el.value);
		el.value = "";
		return value;
	}
	,__class__: todomvc_view_Header
});
var todomvc_view_Item = function(api,state,children) {
	doom_Component.call(this,api,state,children);
};
todomvc_view_Item.__name__ = ["todomvc","view","Item"];
todomvc_view_Item.__super__ = doom_Component;
todomvc_view_Item.prototype = $extend(doom_Component.prototype,{
	render: function() {
		var _g1 = new haxe_ds_StringMap();
		var _g = new haxe_ds_StringMap();
		var value1 = this.state.item.completed;
		if(__map_reserved.completed != null) _g.setReserved("completed",value1); else _g.h["completed"] = value1;
		var value2 = this.state.editing;
		if(__map_reserved.editing != null) _g.setReserved("editing",value2); else _g.h["editing"] = value2;
		var value = doom__$AttributeValue_AttributeValue_$Impl_$.fromMap(_g);
		if(__map_reserved["class"] != null) _g1.setReserved("class",value); else _g1.h["class"] = value;
		var value3 = doom__$AttributeValue_AttributeValue_$Impl_$.fromHandler($bind(this,this.handleDblClick));
		if(__map_reserved.dblclick != null) _g1.setReserved("dblclick",value3); else _g1.h["dblclick"] = value3;
		var _g2 = new haxe_ds_StringMap();
		var value4 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("view");
		if(__map_reserved["class"] != null) _g2.setReserved("class",value4); else _g2.h["class"] = value4;
		var _g3 = new haxe_ds_StringMap();
		var value5 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("toggle");
		if(__map_reserved["class"] != null) _g3.setReserved("class",value5); else _g3.h["class"] = value5;
		var value6 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("checkbox");
		if(__map_reserved.type != null) _g3.setReserved("type",value6); else _g3.h["type"] = value6;
		var value7 = doom__$AttributeValue_AttributeValue_$Impl_$.fromBool(this.state.item.completed);
		if(__map_reserved.checked != null) _g3.setReserved("checked",value7); else _g3.h["checked"] = value7;
		var value8 = doom__$AttributeValue_AttributeValue_$Impl_$.fromHandler(($_=this.api,$bind($_,$_.toggle)));
		if(__map_reserved.change != null) _g3.setReserved("change",value8); else _g3.h["change"] = value8;
		var tmp = doom__$Node_Node_$Impl_$.el("input",_g3,null,null);
		var tmp1 = doom__$Node_Node_$Impl_$.el("label",null,null,doom_NodeImpl.Text(this.state.item.text));
		var _g4 = new haxe_ds_StringMap();
		var value9 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("destroy");
		if(__map_reserved["class"] != null) _g4.setReserved("class",value9); else _g4.h["class"] = value9;
		var value10 = doom__$AttributeValue_AttributeValue_$Impl_$.fromHandler(($_=this.api,$bind($_,$_.remove)));
		if(__map_reserved.click != null) _g4.setReserved("click",value10); else _g4.h["click"] = value10;
		var tmp2 = doom__$Node_Node_$Impl_$.el("div",_g2,[tmp,tmp1,doom__$Node_Node_$Impl_$.el("button",_g4,null,null)],null);
		var _g5 = new haxe_ds_StringMap();
		var value11 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("edit");
		if(__map_reserved["class"] != null) _g5.setReserved("class",value11); else _g5.h["class"] = value11;
		var value12 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString(this.state.item.text);
		if(__map_reserved.value != null) _g5.setReserved("value",value12); else _g5.h["value"] = value12;
		var value13 = doom__$AttributeValue_AttributeValue_$Impl_$.fromHandler($bind(this,this.handleBlur));
		if(__map_reserved.blur != null) _g5.setReserved("blur",value13); else _g5.h["blur"] = value13;
		var value14 = doom__$AttributeValue_AttributeValue_$Impl_$.fromEventHandler($bind(this,this.handleKeydown));
		if(__map_reserved.keyup != null) _g5.setReserved("keyup",value14); else _g5.h["keyup"] = value14;
		return doom__$Node_Node_$Impl_$.el("li",_g1,[tmp2,doom__$Node_Node_$Impl_$.el("input",_g5,null,null)],null);
	}
	,handleDblClick: function() {
		this.state.editing = true;
		this.update(this.state);
		this.getInput().select();
	}
	,handleBlur: function() {
		if(!this.state.editing) return;
		this.state.editing = false;
		var value = this.getInputValueAndTrim();
		if(thx_Strings.isEmpty(value)) this.api.remove(); else if(value != this.state.item.text) this.api.updateText(value); else this.update({ item : this.state.item, editing : false});
	}
	,handleKeydown: function(e) {
		if(e.which != 13) return;
		this.handleBlur();
	}
	,getInput: function() {
		return this.element.querySelector("input.edit");
	}
	,getInputValueAndTrim: function() {
		var input = this.getInput();
		return input.value = StringTools.trim(input.value);
	}
	,__class__: todomvc_view_Item
});
var todomvc_view_List = function(api,state,children) {
	doom_Component.call(this,api,state,children);
};
todomvc_view_List.__name__ = ["todomvc","view","List"];
todomvc_view_List.__super__ = doom_Component;
todomvc_view_List.prototype = $extend(doom_Component.prototype,{
	render: function() {
		var _g = new haxe_ds_StringMap();
		var value = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("main");
		if(__map_reserved["class"] != null) _g.setReserved("class",value); else _g.h["class"] = value;
		var _g1 = new haxe_ds_StringMap();
		var value1 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("toggle-all");
		if(__map_reserved["class"] != null) _g1.setReserved("class",value1); else _g1.h["class"] = value1;
		var value2 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("checkbox");
		if(__map_reserved.type != null) _g1.setReserved("type",value2); else _g1.h["type"] = value2;
		var value3 = doom__$AttributeValue_AttributeValue_$Impl_$.fromBool(this.state.allCompleted);
		if(__map_reserved.checked != null) _g1.setReserved("checked",value3); else _g1.h["checked"] = value3;
		var value4 = doom__$AttributeValue_AttributeValue_$Impl_$.fromHandler(($_=this.api,$bind($_,$_.toggleAll)));
		if(__map_reserved.change != null) _g1.setReserved("change",value4); else _g1.h["change"] = value4;
		var tmp = doom__$Node_Node_$Impl_$.el("input",_g1,null,null);
		var _g2 = new haxe_ds_StringMap();
		var value5 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("toggle-all");
		if(__map_reserved["for"] != null) _g2.setReserved("for",value5); else _g2.h["for"] = value5;
		var tmp1 = doom__$Node_Node_$Impl_$.el("label",_g2,null,doom_NodeImpl.Text("Mark all as complete"));
		var _g3 = new haxe_ds_StringMap();
		var value6 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("todo-list");
		if(__map_reserved["class"] != null) _g3.setReserved("class",value6); else _g3.h["class"] = value6;
		var _g4 = [];
		var tmp2 = HxOverrides.iter(this.state.items);
		while(tmp2.hasNext()) {
			var item = tmp2.next();
			_g4.push(doom_NodeImpl.ComponentNode(new todomvc_view_Item({ remove : (function(id,f) {
				return function() {
					f[0](id[0]);
				};
			})([item.id],[($_=this.api,$bind($_,$_.remove))]), toggle : (function(id1,f1) {
				return function() {
					f1[0](id1[0]);
				};
			})([item.id],[($_=this.api,$bind($_,$_.toggle))]), updateText : (function(id2,f2) {
				return function(a1) {
					f2[0](id2[0],a1);
				};
			})([item.id],[($_=this.api,$bind($_,$_.updateText))])},{ item : item, editing : false})));
		}
		return doom__$Node_Node_$Impl_$.el("section",_g,[tmp,tmp1,doom__$Node_Node_$Impl_$.el("ul",_g3,_g4,null)],null);
	}
	,__class__: todomvc_view_List
});
function $iterator(o) { if( o instanceof Array ) return function() { return HxOverrides.iter(o); }; return typeof(o.iterator) == 'function' ? $bind(o,o.iterator) : o.iterator; }
var $_, $fid = 0;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $fid++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = function(){ return f.method.apply(f.scope, arguments); }; f.scope = o; f.method = m; o.hx__closures__[m.__id__] = f; } return f; }
if(Array.prototype.indexOf) HxOverrides.indexOf = function(a,o,i) {
	return Array.prototype.indexOf.call(a,o,i);
};
String.prototype.__class__ = String;
String.__name__ = ["String"];
Array.__name__ = ["Array"];
Date.prototype.__class__ = Date;
Date.__name__ = ["Date"];
var Int = { __name__ : ["Int"]};
var Dynamic = { __name__ : ["Dynamic"]};
var Float = Number;
Float.__name__ = ["Float"];
var Bool = Boolean;
Bool.__ename__ = ["Bool"];
var Class = { __name__ : ["Class"]};
var Enum = { };
if(Array.prototype.map == null) Array.prototype.map = function(f) {
	var a = [];
	var _g1 = 0;
	var _g = this.length;
	while(_g1 < _g) {
		var i = _g1++;
		a[i] = f(this[i]);
	}
	return a;
};
if(Array.prototype.filter == null) Array.prototype.filter = function(f1) {
	var a1 = [];
	var _g11 = 0;
	var _g2 = this.length;
	while(_g11 < _g2) {
		var i1 = _g11++;
		var e = this[i1];
		if(f1(e)) a1.push(e);
	}
	return a1;
};
var __map_reserved = {}
var ArrayBuffer = $global.ArrayBuffer || js_html_compat_ArrayBuffer;
if(ArrayBuffer.prototype.slice == null) ArrayBuffer.prototype.slice = js_html_compat_ArrayBuffer.sliceImpl;
var Uint8Array = $global.Uint8Array || js_html_compat_Uint8Array._new;

      // Production steps of ECMA-262, Edition 5, 15.4.4.21
      // Reference: http://es5.github.io/#x15.4.4.21
      if (!Array.prototype.reduce) {
        Array.prototype.reduce = function(callback /*, initialValue*/) {
          'use strict';
          if (this == null) {
            throw new TypeError('Array.prototype.reduce called on null or undefined');
          }
          if (typeof callback !== 'function') {
            throw new TypeError(callback + ' is not a function');
          }
          var t = Object(this), len = t.length >>> 0, k = 0, value;
          if (arguments.length == 2) {
            value = arguments[1];
          } else {
            while (k < len && ! k in t) {
              k++;
            }
            if (k >= len) {
              throw new TypeError('Reduce of empty array with no initial value');
            }
            value = t[k++];
          }
          for (; k < len; k++) {
            if (k in t) {
              value = callback(value, t[k], k, t);
            }
          }
          return value;
        };
      }
    ;
var scope = ("undefined" !== typeof window && window) || ("undefined" !== typeof global && global) || this;
if(!scope.setImmediate) scope.setImmediate = function(callback) {
	scope.setTimeout(callback,0);
};
var lastTime = 0;
var vendors = ["webkit","moz"];
var x = 0;
while(x < vendors.length && !scope.requestAnimationFrame) {
	scope.requestAnimationFrame = scope[vendors[x] + "RequestAnimationFrame"];
	scope.cancelAnimationFrame = scope[vendors[x] + "CancelAnimationFrame"] || scope[vendors[x] + "CancelRequestAnimationFrame"];
	x++;
}
if(!scope.requestAnimationFrame) scope.requestAnimationFrame = function(callback1) {
	var currTime = new Date().getTime();
	var timeToCall = Math.max(0,16 - (currTime - lastTime));
	var id = scope.setTimeout(function() {
		callback1(currTime + timeToCall);
	},timeToCall);
	lastTime = currTime + timeToCall;
	return id;
};
if(!scope.cancelAnimationFrame) scope.cancelAnimationFrame = function(id1) {
	scope.clearTimeout(id1);
};
if(typeof(scope.performance) == "undefined") scope.performance = { };
if(typeof(scope.performance.now) == "undefined") {
	var nowOffset = new Date().getTime();
	if(scope.performance.timing && scope.performance.timing.navigationStart) nowOffset = scope.performance.timing.navigationStart;
	scope.performance.now = (function($this) {
		var $r;
		var now = function() {
			return new Date() - nowOffset;
		};
		$r = now;
		return $r;
	}(this));
}
Doom.namespaces = (function($this) {
	var $r;
	var _g = new haxe_ds_StringMap();
	if(__map_reserved.svg != null) _g.setReserved("svg","http://www.w3.org/2000/svg"); else _g.h["svg"] = "http://www.w3.org/2000/svg";
	$r = _g;
	return $r;
}(this));
dots_Html.pattern = new EReg("[<]([^> ]+)","");
dots_Query.doc = document;
js_Boot.__toStr = {}.toString;
js_html_compat_Uint8Array.BYTES_PER_ELEMENT = 1;
Main.main();
})(typeof console != "undefined" ? console : {log:function(){}}, typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
