// Generated by Haxe
(function (console, $global) { "use strict";
var $estr = function() { return js_Boot.__string_rec(this,''); };
function $extend(from, fields) {
	function Inherit() {} Inherit.prototype = from; var proto = new Inherit();
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var Doom = function() { };
Doom.__name__ = ["Doom"];
Doom.mount = function(component,ref) {
	if(null == ref) throw new js__$Boot_HaxeError("reference element is set to null");
	ref.innerHTML = "";
	component.init();
	ref.appendChild(component.element);
};
var EReg = function(r,opt) {
	opt = opt.split("u").join("");
	this.r = new RegExp(r,opt);
};
EReg.__name__ = ["EReg"];
EReg.prototype = {
	match: function(s) {
		if(this.r.global) this.r.lastIndex = 0;
		this.r.m = this.r.exec(s);
		this.r.s = s;
		return this.r.m != null;
	}
	,matched: function(n) {
		var tmp;
		if(this.r.m != null && n >= 0 && n < this.r.m.length) tmp = this.r.m[n]; else throw new js__$Boot_HaxeError("EReg::matched");
		return tmp;
	}
	,__class__: EReg
};
var HxOverrides = function() { };
HxOverrides.__name__ = ["HxOverrides"];
HxOverrides.dateStr = function(date) {
	var m = date.getMonth() + 1;
	var d = date.getDate();
	var h = date.getHours();
	var mi = date.getMinutes();
	var s = date.getSeconds();
	return date.getFullYear() + "-" + (m < 10?"0" + m:"" + m) + "-" + (d < 10?"0" + d:"" + d) + " " + (h < 10?"0" + h:"" + h) + ":" + (mi < 10?"0" + mi:"" + mi) + ":" + (s < 10?"0" + s:"" + s);
};
HxOverrides.cca = function(s,index) {
	var x = s.charCodeAt(index);
	if(x != x) return undefined;
	return x;
};
HxOverrides.substr = function(s,pos,len) {
	if(len == null) len = s.length; else if(len < 0) {
		if(pos == 0) len = s.length + len; else return "";
	}
	if(pos < 0) {
		pos = s.length + pos;
		if(pos < 0) pos = 0;
	}
	return s.substr(pos,len);
};
HxOverrides.indexOf = function(a,obj,i) {
	var len = a.length;
	if(i < 0) {
		i += len;
		if(i < 0) i = 0;
	}
	while(i < len) {
		if(a[i] === obj) return i;
		i++;
	}
	return -1;
};
HxOverrides.remove = function(a,obj) {
	var i = HxOverrides.indexOf(a,obj,0);
	if(i == -1) return false;
	a.splice(i,1);
	return true;
};
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var Main = function() { };
Main.__name__ = ["Main"];
Main.main = function() {
	var store = lies_Store.create(function(state,action) {
		var tmp;
		var _0 = todomvc_data_Reducers.todoApp(state,action);
		tmp = { _0 : _0, _1 : []};
		return tmp;
	},{ visibilityFilter : Main.getFilterFromHash(), todos : Main.getTodosFromLocalStorage()});
	var tmp1;
	var f = function(state1) {
		window.localStorage.setItem("TodoMVC-Doom",JSON.stringify(state1.todos));
	};
	tmp1 = function(state2,_,_1) {
		f(state2);
	};
	store.subscribe(tmp1);
	var tmp2;
	var f1 = function(state3) {
		var tmp4;
		var _g = state3.visibilityFilter;
		switch(_g[1]) {
		case 2:
			tmp4 = "/active";
			break;
		case 1:
			tmp4 = "/completed";
			break;
		default:
			tmp4 = "";
		}
		window.location.hash = tmp4;
	};
	tmp2 = function(state4,_2,_3) {
		f1(state4);
	};
	store.subscribe(tmp2);
	var tmp3;
	var f2 = function(action1) {
		window.console.log(thx_Enums.string(action1));
	};
	tmp3 = function(_4,_5,action2) {
		f2(action2);
	};
	store.subscribe(tmp3);
	Doom.mount(new todomvc_view_App(store),dots_Query.first("section.todoapp"));
};
Main.getFilterFromHash = function() {
	var hash = thx_Strings.trimCharsLeft(window.location.hash,"#");
	var tmp;
	switch(hash) {
	case "/active":
		tmp = todomvc_data_VisibilityFilter.ShowActive;
		break;
	case "/completed":
		tmp = todomvc_data_VisibilityFilter.ShowCompleted;
		break;
	default:
		tmp = todomvc_data_VisibilityFilter.ShowAll;
	}
	return tmp;
};
Main.getTodosFromLocalStorage = function() {
	var v = window.localStorage.getItem("TodoMVC-Doom");
	if(v != null && v.length > 0) return JSON.parse(v); else return [];
};
Math.__name__ = ["Math"];
var Reflect = function() { };
Reflect.__name__ = ["Reflect"];
Reflect.field = function(o,field) {
	try {
		return o[field];
	} catch( e ) {
		haxe_CallStack.lastException = e;
		if (e instanceof js__$Boot_HaxeError) e = e.val;
		return null;
	}
};
Reflect.fields = function(o) {
	var a = [];
	if(o != null) {
		var hasOwnProperty = Object.prototype.hasOwnProperty;
		for( var f in o ) {
		if(f != "__id__" && f != "hx__closures__" && hasOwnProperty.call(o,f)) a.push(f);
		}
	}
	return a;
};
var Std = function() { };
Std.__name__ = ["Std"];
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
Std.parseInt = function(x) {
	var v = parseInt(x,10);
	if(v == 0 && (HxOverrides.cca(x,1) == 120 || HxOverrides.cca(x,1) == 88)) v = parseInt(x);
	if(isNaN(v)) return null;
	return v;
};
var StringBuf = function() {
	this.b = "";
};
StringBuf.__name__ = ["StringBuf"];
StringBuf.prototype = {
	__class__: StringBuf
};
var StringTools = function() { };
StringTools.__name__ = ["StringTools"];
StringTools.isSpace = function(s,pos) {
	var c = HxOverrides.cca(s,pos);
	return c > 8 && c < 14 || c == 32;
};
StringTools.ltrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,r)) r++;
	if(r > 0) return HxOverrides.substr(s,r,l - r); else return s;
};
StringTools.rtrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,l - r - 1)) r++;
	if(r > 0) return HxOverrides.substr(s,0,l - r); else return s;
};
StringTools.trim = function(s) {
	return StringTools.ltrim(StringTools.rtrim(s));
};
StringTools.replace = function(s,sub,by) {
	return s.split(sub).join(by);
};
var ValueType = { __ename__ : true, __constructs__ : ["TNull","TInt","TFloat","TBool","TObject","TFunction","TClass","TEnum","TUnknown"] };
ValueType.TNull = ["TNull",0];
ValueType.TNull.toString = $estr;
ValueType.TNull.__enum__ = ValueType;
ValueType.TInt = ["TInt",1];
ValueType.TInt.toString = $estr;
ValueType.TInt.__enum__ = ValueType;
ValueType.TFloat = ["TFloat",2];
ValueType.TFloat.toString = $estr;
ValueType.TFloat.__enum__ = ValueType;
ValueType.TBool = ["TBool",3];
ValueType.TBool.toString = $estr;
ValueType.TBool.__enum__ = ValueType;
ValueType.TObject = ["TObject",4];
ValueType.TObject.toString = $estr;
ValueType.TObject.__enum__ = ValueType;
ValueType.TFunction = ["TFunction",5];
ValueType.TFunction.toString = $estr;
ValueType.TFunction.__enum__ = ValueType;
ValueType.TClass = function(c) { var $x = ["TClass",6,c]; $x.__enum__ = ValueType; $x.toString = $estr; return $x; };
ValueType.TEnum = function(e) { var $x = ["TEnum",7,e]; $x.__enum__ = ValueType; $x.toString = $estr; return $x; };
ValueType.TUnknown = ["TUnknown",8];
ValueType.TUnknown.toString = $estr;
ValueType.TUnknown.__enum__ = ValueType;
var Type = function() { };
Type.__name__ = ["Type"];
Type.getClassName = function(c) {
	var a = c.__name__;
	if(a == null) return null;
	return a.join(".");
};
Type.createInstance = function(cl,args) {
	var _g = args.length;
	switch(_g) {
	case 0:
		return new cl();
	case 1:
		return new cl(args[0]);
	case 2:
		return new cl(args[0],args[1]);
	case 3:
		return new cl(args[0],args[1],args[2]);
	case 4:
		return new cl(args[0],args[1],args[2],args[3]);
	case 5:
		return new cl(args[0],args[1],args[2],args[3],args[4]);
	case 6:
		return new cl(args[0],args[1],args[2],args[3],args[4],args[5]);
	case 7:
		return new cl(args[0],args[1],args[2],args[3],args[4],args[5],args[6]);
	case 8:
		return new cl(args[0],args[1],args[2],args[3],args[4],args[5],args[6],args[7]);
	default:
		throw new js__$Boot_HaxeError("Too many arguments");
	}
	return null;
};
Type["typeof"] = function(v) {
	var _g = typeof(v);
	switch(_g) {
	case "boolean":
		return ValueType.TBool;
	case "string":
		return ValueType.TClass(String);
	case "number":
		if(Math.ceil(v) == v % 2147483648.0) return ValueType.TInt;
		return ValueType.TFloat;
	case "object":
		if(v == null) return ValueType.TNull;
		var e = v.__enum__;
		if(e != null) return ValueType.TEnum(e);
		var c = js_Boot.getClass(v);
		if(c != null) return ValueType.TClass(c);
		return ValueType.TObject;
	case "function":
		if(v.__name__ || v.__ename__) return ValueType.TObject;
		return ValueType.TFunction;
	case "undefined":
		return ValueType.TNull;
	default:
		return ValueType.TUnknown;
	}
};
Type.enumEq = function(a,b) {
	if(a == b) return true;
	try {
		if(a[0] != b[0]) return false;
		var _g1 = 2;
		var _g = a.length;
		while(_g1 < _g) {
			var i = _g1++;
			if(!Type.enumEq(a[i],b[i])) return false;
		}
		var e = a.__enum__;
		if(e != b.__enum__ || e == null) return false;
	} catch( e1 ) {
		haxe_CallStack.lastException = e1;
		if (e1 instanceof js__$Boot_HaxeError) e1 = e1.val;
		return false;
	}
	return true;
};
var doom__$AttributeValue_AttributeValue_$Impl_$ = {};
doom__$AttributeValue_AttributeValue_$Impl_$.__name__ = ["doom","_AttributeValue","AttributeValue_Impl_"];
doom__$AttributeValue_AttributeValue_$Impl_$.fromString = function(s) {
	return doom_AttributeValueImpl.StringAttribute(s);
};
doom__$AttributeValue_AttributeValue_$Impl_$.fromMap = function(map) {
	var values = [];
	var $it0 = map.keys();
	while( $it0.hasNext() ) {
		var key = $it0.next();
		if(__map_reserved[key] != null?map.getReserved(key):map.h[key]) values.push(key);
	}
	return doom_AttributeValueImpl.StringAttribute(values.join(" "));
};
doom__$AttributeValue_AttributeValue_$Impl_$.fromBool = function(b) {
	return doom_AttributeValueImpl.BoolAttribute(b);
};
doom__$AttributeValue_AttributeValue_$Impl_$.fromHandler = function(f) {
	return doom_AttributeValueImpl.EventAttribute(function(e) {
		e.preventDefault();
		f();
	});
};
doom__$AttributeValue_AttributeValue_$Impl_$.fromEventHandler = function(f) {
	return doom_AttributeValueImpl.EventAttribute(f);
};
doom__$AttributeValue_AttributeValue_$Impl_$.equalsTo = function(this1,that) {
	var tmp;
	switch(this1[1]) {
	case 0:
		switch(that[1]) {
		case 0:
			tmp = this1[2] == that[2];
			break;
		default:
			tmp = false;
		}
		break;
	case 1:
		switch(that[1]) {
		case 1:
			tmp = this1[2] == that[2];
			break;
		default:
			tmp = false;
		}
		break;
	default:
		tmp = false;
	}
	return tmp;
};
doom__$AttributeValue_AttributeValue_$Impl_$.notEqualsTo = function(this1,that) {
	return !doom__$AttributeValue_AttributeValue_$Impl_$.equalsTo(this1,that);
};
var doom_AttributeValueImpl = { __ename__ : true, __constructs__ : ["BoolAttribute","StringAttribute","EventAttribute"] };
doom_AttributeValueImpl.BoolAttribute = function(b) { var $x = ["BoolAttribute",0,b]; $x.__enum__ = doom_AttributeValueImpl; $x.toString = $estr; return $x; };
doom_AttributeValueImpl.StringAttribute = function(s) { var $x = ["StringAttribute",1,s]; $x.__enum__ = doom_AttributeValueImpl; $x.toString = $estr; return $x; };
doom_AttributeValueImpl.EventAttribute = function(f) { var $x = ["EventAttribute",2,f]; $x.__enum__ = doom_AttributeValueImpl; $x.toString = $estr; return $x; };
var doom_IComponent = function() { };
doom_IComponent.__name__ = ["doom","IComponent"];
doom_IComponent.prototype = {
	__class__: doom_IComponent
};
var doom_Component = function(state) {
	this.state = state;
	this.node = this.render();
};
doom_Component.__name__ = ["doom","Component"];
doom_Component.__interfaces__ = [doom_IComponent];
doom_Component.prototype = {
	init: function() {
		this.element = doom_HtmlNode.toHtml(this.node);
	}
	,updateNode: function(oldNode) {
		var newNode = this.render();
		switch(newNode[1]) {
		case 0:
			break;
		default:
			throw new thx_Error("Component can (and must) return only element nodes",null,{ fileName : "Component.hx", lineNumber : 25, className : "doom.Component", methodName : "updateNode"});
		}
		var patches = doom__$Node_Node_$Impl_$.diff(oldNode,newNode);
		doom_HtmlNode.applyPatches(patches,this.element);
		this.node = newNode;
	}
	,render: function() {
		throw new thx_error_AbstractMethod({ fileName : "Component.hx", lineNumber : 33, className : "doom.Component", methodName : "render"});
	}
	,update: function(newState) {
		var oldState = this.state;
		this.state = newState;
		if(!this.shouldRender(oldState,newState)) return;
		this.updateNode(this.node);
	}
	,shouldRender: function(oldState,newState) {
		return true;
	}
	,__class__: doom_Component
};
var thx__$Set_Set_$Impl_$ = {};
thx__$Set_Set_$Impl_$.__name__ = ["thx","_Set","Set_Impl_"];
thx__$Set_Set_$Impl_$.createString = function(it) {
	var map = new haxe_ds_StringMap();
	var set = map;
	if(null != it) thx__$Set_Set_$Impl_$.pushMany(set,it);
	return set;
};
thx__$Set_Set_$Impl_$.add = function(this1,v) {
	var tmp;
	if(this1.exists(v)) tmp = false; else {
		this1.set(v,true);
		tmp = true;
	}
	return tmp;
};
thx__$Set_Set_$Impl_$.copy = function(this1) {
	var inst = thx__$Set_Set_$Impl_$.empty(this1);
	var $it0 = this1.keys();
	while( $it0.hasNext() ) {
		var k = $it0.next();
		inst.set(k,true);
	}
	return inst;
};
thx__$Set_Set_$Impl_$.empty = function(this1) {
	var inst = Type.createInstance(this1 == null?null:js_Boot.getClass(this1),[]);
	return inst;
};
thx__$Set_Set_$Impl_$.filter = function(this1,predicate) {
	return thx__$Set_Set_$Impl_$.reduce(this1,function(acc,v) {
		if(predicate(v)) thx__$Set_Set_$Impl_$.add(acc,v);
		return acc;
	},thx__$Set_Set_$Impl_$.empty(this1));
};
thx__$Set_Set_$Impl_$.map = function(this1,f) {
	return thx__$Set_Set_$Impl_$.reduce(this1,function(acc,v) {
		acc.push(f(v));
		return acc;
	},[]);
};
thx__$Set_Set_$Impl_$.pushMany = function(this1,values) {
	var $it0 = $iterator(values)();
	while( $it0.hasNext() ) {
		var value = $it0.next();
		this1.set(value,true);
	}
};
thx__$Set_Set_$Impl_$.reduce = function(this1,handler,acc) {
	var $it0 = $iterator(thx__$Set_Set_$Impl_$)(this1);
	while( $it0.hasNext() ) {
		var v = $it0.next();
		acc = handler(acc,v);
	}
	return acc;
};
thx__$Set_Set_$Impl_$.iterator = function(this1) {
	return this1.keys();
};
var doom_HtmlNode = function() { };
doom_HtmlNode.__name__ = ["doom","HtmlNode"];
doom_HtmlNode.toHtml = function(node) {
	var tmp;
	var _g = node;
	switch(_g[1]) {
	case 0:
		var children = _g[4];
		var attributes = _g[3];
		var name = _g[2];
		tmp = doom_HtmlNode.createElement(name,attributes,children);
		break;
	case 1:
		var text = _g[2];
		tmp = dots_Html.parse(text);
		break;
	case 2:
		var text1 = _g[2];
		tmp = window.document.createTextNode(text1);
		break;
	case 3:
		var text2 = _g[2];
		tmp = doom_HtmlNode.createComment(text2);
		break;
	case 4:
		var comp = _g[2];
		comp.init();
		tmp = comp.element;
		break;
	}
	return tmp;
};
doom_HtmlNode.createElement = function(name,attributes,children) {
	var colonPos = name.indexOf(":");
	var tmp;
	if(colonPos > 0) {
		var prefix = name.substring(0,colonPos);
		var name1 = name.substring(colonPos + 1);
		var tmp1;
		var _this = Doom.namespaces;
		if(__map_reserved[prefix] != null) tmp1 = _this.getReserved(prefix); else tmp1 = _this.h[prefix];
		var ns = tmp1;
		if(null == ns) throw new thx_Error("element prefix \"" + prefix + "\" is not associated to any namespace. Add the right namespace to Doom.namespaces.",null,{ fileName : "HtmlNode.hx", lineNumber : 37, className : "doom.HtmlNode", methodName : "createElement"});
		tmp = window.document.createElementNS(ns,name1);
	} else tmp = window.document.createElement(name);
	var el = tmp;
	var $it0 = attributes.keys();
	while( $it0.hasNext() ) {
		var key = $it0.next();
		var value = __map_reserved[key] != null?attributes.getReserved(key):attributes.h[key];
		switch(value[1]) {
		case 1:
			var s = value[2];
			if(s != null && s.length > 0) el.setAttribute(key,s); else {
			}
			break;
		case 0:
			var b = value[2];
			if(b) el.setAttribute(key,""); else {
			}
			break;
		case 2:
			var e = value[2];
			doom_HtmlNode.addEvent(el,key,e);
			break;
		default:
		}
	}
	doom_HtmlNode.trigger(el,"create");
	thx_Timer.immediate(function() {
		doom_HtmlNode.trigger(el,"mount");
	});
	var _g = 0;
	while(_g < children.length) {
		var child = children[_g];
		++_g;
		var n = doom_HtmlNode.toHtml(child);
		if(null != n) el.appendChild(n);
	}
	return el;
};
doom_HtmlNode.createComment = function(comment) {
	return window.document.createComment(comment);
};
doom_HtmlNode.applyPatches = function(patches,node) {
	var _g = 0;
	while(_g < patches.length) {
		var patch = patches[_g];
		++_g;
		doom_HtmlNode.applyPatch(patch,node);
	}
};
doom_HtmlNode.trigger = function(el,name) {
	var event = new CustomEvent(name);
	el.dispatchEvent(event);
};
doom_HtmlNode.addEvent = function(el,name,handler) {
	el["on" + name] = handler;
	var tmp;
	var _this = doom_HtmlNode.customEvents;
	if(__map_reserved[name] != null) tmp = _this.existsReserved(name); else tmp = _this.h.hasOwnProperty(name);
	if(tmp) el.addEventListener(name,handler,false);
};
doom_HtmlNode.applyPatch = function(patch,node) {
	{
		var _g = node.nodeType;
		var p = patch;
		switch(patch[1]) {
		case 0:
			var n = _g;
			switch(_g) {
			case 1:
				var text = patch[2];
				node.appendChild(window.document.createTextNode(text));
				break;
			default:
				throw new thx_Error("cannot apply patch " + Std.string(p) + " on " + n,null,{ fileName : "HtmlNode.hx", lineNumber : 136, className : "doom.HtmlNode", methodName : "applyPatch"});
			}
			break;
		case 1:
			var n1 = _g;
			switch(_g) {
			case 1:
				var text1 = patch[2];
				node.appendChild(dots_Html.parse(text1));
				break;
			default:
				throw new thx_Error("cannot apply patch " + Std.string(p) + " on " + n1,null,{ fileName : "HtmlNode.hx", lineNumber : 136, className : "doom.HtmlNode", methodName : "applyPatch"});
			}
			break;
		case 2:
			var n2 = _g;
			switch(_g) {
			case 1:
				var text2 = patch[2];
				node.appendChild(doom_HtmlNode.createComment(text2));
				break;
			default:
				throw new thx_Error("cannot apply patch " + Std.string(p) + " on " + n2,null,{ fileName : "HtmlNode.hx", lineNumber : 136, className : "doom.HtmlNode", methodName : "applyPatch"});
			}
			break;
		case 3:
			var n3 = _g;
			switch(_g) {
			case 1:
				var name = patch[2];
				var children = patch[4];
				var attributes = patch[3];
				var el = doom_HtmlNode.createElement(name,attributes,children);
				node.appendChild(el);
				doom_HtmlNode.trigger(el,"mount");
				break;
			default:
				throw new thx_Error("cannot apply patch " + Std.string(p) + " on " + n3,null,{ fileName : "HtmlNode.hx", lineNumber : 136, className : "doom.HtmlNode", methodName : "applyPatch"});
			}
			break;
		case 4:
			node.parentNode.removeChild(node);
			break;
		case 5:
			var n4 = _g;
			switch(_g) {
			case 1:
				var name1 = patch[2];
				node.removeAttribute(name1);
				break;
			default:
				throw new thx_Error("cannot apply patch " + Std.string(p) + " on " + n4,null,{ fileName : "HtmlNode.hx", lineNumber : 136, className : "doom.HtmlNode", methodName : "applyPatch"});
			}
			break;
		case 6:
			var n5 = _g;
			switch(_g) {
			case 1:
				var name2 = patch[2];
				var value = patch[3];
				switch(value[1]) {
				case 1:
					var s = value[2];
					if(s != null && s.length > 0) node.setAttribute(name2,s); else node.removeAttribute(name2);
					break;
				case 0:
					var b = value[2];
					if(b) node.setAttribute(name2,name2); else node.removeAttribute(name2);
					break;
				case 2:
					var e = value[2];
					doom_HtmlNode.addEvent(node,name2,e);
					break;
				}
				break;
			default:
				throw new thx_Error("cannot apply patch " + Std.string(p) + " on " + n5,null,{ fileName : "HtmlNode.hx", lineNumber : 136, className : "doom.HtmlNode", methodName : "applyPatch"});
			}
			break;
		case 7:
			var children1 = patch[4];
			var attributes1 = patch[3];
			var name3 = patch[2];
			var parent = node.parentNode;
			var el1 = doom_HtmlNode.createElement(name3,attributes1,children1);
			parent.replaceChild(el1,node);
			doom_HtmlNode.trigger(el1,"mount");
			break;
		case 8:
			var text3 = patch[2];
			var parent1 = node.parentNode;
			parent1.replaceChild(window.document.createTextNode(text3),node);
			break;
		case 9:
			var text4 = patch[2];
			var parent2 = node.parentNode;
			parent2.replaceChild(window.document.createTextNode(text4),node);
			break;
		case 10:
			var text5 = patch[2];
			var parent3 = node.parentNode;
			parent3.replaceChild(doom_HtmlNode.createComment(text5),node);
			break;
		case 11:
			var n6 = _g;
			switch(_g) {
			case 3:
				var newcontent = patch[2];
				node.nodeValue = newcontent;
				break;
			case 8:
				var newcontent1 = patch[2];
				node.nodeValue = newcontent1;
				break;
			default:
				throw new thx_Error("cannot apply patch " + Std.string(p) + " on " + n6,null,{ fileName : "HtmlNode.hx", lineNumber : 136, className : "doom.HtmlNode", methodName : "applyPatch"});
			}
			break;
		case 12:
			var n7 = _g;
			switch(_g) {
			case 1:
				var index = patch[2];
				var patches = patch[3];
				var n8 = node.childNodes.item(index);
				doom_HtmlNode.applyPatches(patches,n8);
				break;
			default:
				throw new thx_Error("cannot apply patch " + Std.string(p) + " on " + n7,null,{ fileName : "HtmlNode.hx", lineNumber : 136, className : "doom.HtmlNode", methodName : "applyPatch"});
			}
			break;
		}
	}
};
var doom__$Node_Node_$Impl_$ = {};
doom__$Node_Node_$Impl_$.__name__ = ["doom","_Node","Node_Impl_"];
doom__$Node_Node_$Impl_$.el = function(name,attributes,children,child) {
	if(null == attributes) attributes = new haxe_ds_StringMap();
	if(null == children) children = [];
	if(null != child) children.push(child);
	return doom_NodeImpl.Element(name,attributes,children);
};
doom__$Node_Node_$Impl_$.diffAttributes = function(a,b) {
	var ka = thx__$Set_Set_$Impl_$.createString(thx_Iterators.toArray(a.keys()));
	var kb = thx__$Set_Set_$Impl_$.createString(thx_Iterators.toArray(b.keys()));
	var tmp;
	var result = thx__$Set_Set_$Impl_$.copy(ka);
	var $it0 = $iterator(thx__$Set_Set_$Impl_$)(kb);
	while( $it0.hasNext() ) {
		var item = $it0.next();
		result.remove(item);
	}
	tmp = result;
	var removed = tmp;
	var tmp1;
	var result1 = thx__$Set_Set_$Impl_$.copy(kb);
	var $it1 = $iterator(thx__$Set_Set_$Impl_$)(ka);
	while( $it1.hasNext() ) {
		var item1 = $it1.next();
		result1.remove(item1);
	}
	tmp1 = result1;
	var added = tmp1;
	var tmp2;
	var result2 = thx__$Set_Set_$Impl_$.empty(ka);
	var $it2 = $iterator(thx__$Set_Set_$Impl_$)(ka);
	while( $it2.hasNext() ) {
		var item2 = $it2.next();
		var tmp6;
		var _this = kb;
		if(__map_reserved[item2] != null) tmp6 = _this.existsReserved(item2); else tmp6 = _this.h.hasOwnProperty(item2);
		if(tmp6) {
			var _this1 = result2;
			if(__map_reserved[item2] != null) _this1.setReserved(item2,true); else _this1.h[item2] = true;
		}
	}
	tmp2 = result2;
	var common = tmp2;
	var tmp3;
	var _e = removed;
	tmp3 = function(f) {
		return thx__$Set_Set_$Impl_$.map(_e,f);
	};
	var tmp4;
	var tmp7;
	var _e2 = common;
	tmp7 = function(predicate) {
		return thx__$Set_Set_$Impl_$.filter(_e2,predicate);
	};
	var _e1 = tmp7(function(_) {
		return doom__$AttributeValue_AttributeValue_$Impl_$.notEqualsTo(__map_reserved[_] != null?a.getReserved(_):a.h[_],__map_reserved[_] != null?b.getReserved(_):b.h[_]);
	});
	tmp4 = function(f1) {
		return thx__$Set_Set_$Impl_$.map(_e1,f1);
	};
	var tmp5;
	var _e3 = added;
	tmp5 = function(f2) {
		return thx__$Set_Set_$Impl_$.map(_e3,f2);
	};
	return tmp3(function(_1) {
		return doom_Patch.RemoveAttribute(_1);
	}).concat(tmp4(function(_2) {
		return doom_Patch.SetAttribute(_2,__map_reserved[_2] != null?b.getReserved(_2):b.h[_2]);
	})).concat(tmp5(function(_3) {
		return doom_Patch.SetAttribute(_3,__map_reserved[_3] != null?b.getReserved(_3):b.h[_3]);
	}));
};
doom__$Node_Node_$Impl_$.diffAdd = function(node) {
	var tmp;
	switch(node[1]) {
	case 0:
		tmp = [doom_Patch.AddElement(node[2],node[3],node[4])];
		break;
	case 2:
		tmp = [doom_Patch.AddText(node[2])];
		break;
	case 1:
		tmp = [doom_Patch.AddRaw(node[2])];
		break;
	case 3:
		tmp = [doom_Patch.AddComment(node[2])];
		break;
	case 4:
		tmp = doom__$Node_Node_$Impl_$.diffAdd(node[2].node);
		break;
	}
	return tmp;
};
doom__$Node_Node_$Impl_$.diffNodes = function(a,b) {
	var tmp;
	var a1 = a.length;
	var b1 = b.length;
	if(a1 < b1) tmp = a1; else tmp = b1;
	var min = tmp;
	var result = [];
	var _g1 = min;
	var _g = a.length;
	while(_g1 < _g) {
		var i = _g1++;
		result.push(doom_Patch.PatchChild(a.length - i - 1,[doom_Patch.Remove]));
	}
	var _g11 = min;
	var _g2 = b.length;
	while(_g11 < _g2) {
		var i1 = _g11++;
		result = result.concat(doom__$Node_Node_$Impl_$.diffAdd(b[i1]));
	}
	var _g3 = 0;
	while(_g3 < min) {
		var i2 = _g3++;
		var diff = doom__$Node_Node_$Impl_$.diff(a[i2],b[i2]);
		if(diff.length > 0) result.push(doom_Patch.PatchChild(i2,diff));
	}
	return result;
};
doom__$Node_Node_$Impl_$.diff = function(this1,that) {
	var tmp;
	switch(this1[1]) {
	case 4:
		switch(that[1]) {
		case 4:
			var comp = that[2];
			comp.element = this1[2].element;
			tmp = doom__$Node_Node_$Impl_$.diff(this1,comp.node);
			break;
		case 0:
			tmp = [doom_Patch.ReplaceWithElement(that[2],that[3],that[4])];
			break;
		case 2:
			tmp = [doom_Patch.ReplaceWithText(that[2])];
			break;
		case 1:
			tmp = [doom_Patch.ReplaceWithRaw(that[2])];
			break;
		case 3:
			tmp = [doom_Patch.ReplaceWithComment(that[2])];
			break;
		}
		break;
	case 0:
		switch(that[1]) {
		case 4:
			tmp = doom__$Node_Node_$Impl_$.diff(this1,that[2].node);
			break;
		case 0:
			var n2 = that[2];
			if(this1[2] != n2) tmp = [doom_Patch.ReplaceWithElement(n2,that[3],that[4])]; else tmp = doom__$Node_Node_$Impl_$.diffAttributes(this1[3],that[3]).concat(doom__$Node_Node_$Impl_$.diffNodes(this1[4],that[4]));
			break;
		case 2:
			tmp = [doom_Patch.ReplaceWithText(that[2])];
			break;
		case 1:
			tmp = [doom_Patch.ReplaceWithRaw(that[2])];
			break;
		case 3:
			tmp = [doom_Patch.ReplaceWithComment(that[2])];
			break;
		}
		break;
	case 2:
		switch(that[1]) {
		case 4:
			tmp = doom__$Node_Node_$Impl_$.diff(this1,that[2].node);
			break;
		case 0:
			tmp = [doom_Patch.ReplaceWithElement(that[2],that[3],that[4])];
			break;
		case 2:
			var t2 = that[2];
			if(this1[2] != t2) tmp = [doom_Patch.ContentChanged(t2)]; else tmp = [];
			break;
		case 1:
			tmp = [doom_Patch.ReplaceWithRaw(that[2])];
			break;
		case 3:
			tmp = [doom_Patch.ReplaceWithComment(that[2])];
			break;
		}
		break;
	case 3:
		switch(that[1]) {
		case 4:
			tmp = doom__$Node_Node_$Impl_$.diff(this1,that[2].node);
			break;
		case 0:
			tmp = [doom_Patch.ReplaceWithElement(that[2],that[3],that[4])];
			break;
		case 3:
			var t21 = that[2];
			if(this1[2] != t21) tmp = [doom_Patch.ContentChanged(t21)]; else tmp = [];
			break;
		case 2:
			tmp = [doom_Patch.ReplaceWithText(that[2])];
			break;
		case 1:
			tmp = [doom_Patch.ReplaceWithRaw(that[2])];
			break;
		}
		break;
	default:
		switch(that[1]) {
		case 4:
			tmp = doom__$Node_Node_$Impl_$.diff(this1,that[2].node);
			break;
		case 0:
			tmp = [doom_Patch.ReplaceWithElement(that[2],that[3],that[4])];
			break;
		case 2:
			tmp = [doom_Patch.ReplaceWithText(that[2])];
			break;
		case 1:
			tmp = [doom_Patch.ReplaceWithRaw(that[2])];
			break;
		case 3:
			tmp = [doom_Patch.ReplaceWithComment(that[2])];
			break;
		}
	}
	return tmp;
};
var doom_NodeImpl = { __ename__ : true, __constructs__ : ["Element","Raw","Text","Comment","ComponentNode"] };
doom_NodeImpl.Element = function(name,attributes,children) { var $x = ["Element",0,name,attributes,children]; $x.__enum__ = doom_NodeImpl; $x.toString = $estr; return $x; };
doom_NodeImpl.Raw = function(text) { var $x = ["Raw",1,text]; $x.__enum__ = doom_NodeImpl; $x.toString = $estr; return $x; };
doom_NodeImpl.Text = function(text) { var $x = ["Text",2,text]; $x.__enum__ = doom_NodeImpl; $x.toString = $estr; return $x; };
doom_NodeImpl.Comment = function(text) { var $x = ["Comment",3,text]; $x.__enum__ = doom_NodeImpl; $x.toString = $estr; return $x; };
doom_NodeImpl.ComponentNode = function(comp) { var $x = ["ComponentNode",4,comp]; $x.__enum__ = doom_NodeImpl; $x.toString = $estr; return $x; };
var doom_Patch = { __ename__ : true, __constructs__ : ["AddText","AddRaw","AddComment","AddElement","Remove","RemoveAttribute","SetAttribute","ReplaceWithElement","ReplaceWithText","ReplaceWithRaw","ReplaceWithComment","ContentChanged","PatchChild"] };
doom_Patch.AddText = function(text) { var $x = ["AddText",0,text]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.AddRaw = function(text) { var $x = ["AddRaw",1,text]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.AddComment = function(text) { var $x = ["AddComment",2,text]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.AddElement = function(name,attributes,children) { var $x = ["AddElement",3,name,attributes,children]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.Remove = ["Remove",4];
doom_Patch.Remove.toString = $estr;
doom_Patch.Remove.__enum__ = doom_Patch;
doom_Patch.RemoveAttribute = function(name) { var $x = ["RemoveAttribute",5,name]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.SetAttribute = function(name,value) { var $x = ["SetAttribute",6,name,value]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.ReplaceWithElement = function(name,attributes,children) { var $x = ["ReplaceWithElement",7,name,attributes,children]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.ReplaceWithText = function(text) { var $x = ["ReplaceWithText",8,text]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.ReplaceWithRaw = function(text) { var $x = ["ReplaceWithRaw",9,text]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.ReplaceWithComment = function(text) { var $x = ["ReplaceWithComment",10,text]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.ContentChanged = function(newcontent) { var $x = ["ContentChanged",11,newcontent]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
doom_Patch.PatchChild = function(index,patches) { var $x = ["PatchChild",12,index,patches]; $x.__enum__ = doom_Patch; $x.toString = $estr; return $x; };
var doom_PropertiesComponent = function(prop,state) {
	this.prop = prop;
	doom_Component.call(this,state);
};
doom_PropertiesComponent.__name__ = ["doom","PropertiesComponent"];
doom_PropertiesComponent.__super__ = doom_Component;
doom_PropertiesComponent.prototype = $extend(doom_Component.prototype,{
	__class__: doom_PropertiesComponent
});
var doom_StatelessComponent = function() {
	this.node = this.render();
};
doom_StatelessComponent.__name__ = ["doom","StatelessComponent"];
doom_StatelessComponent.__interfaces__ = [doom_IComponent];
doom_StatelessComponent.prototype = {
	init: function() {
		this.element = doom_HtmlNode.toHtml(this.node);
	}
	,render: function() {
		throw new thx_error_AbstractMethod({ fileName : "StatelessComponent.hx", lineNumber : 27, className : "doom.StatelessComponent", methodName : "render"});
	}
	,__class__: doom_StatelessComponent
};
var doom_PropertiesStatelessComponent = function(prop) {
	this.prop = prop;
	doom_StatelessComponent.call(this);
};
doom_PropertiesStatelessComponent.__name__ = ["doom","PropertiesStatelessComponent"];
doom_PropertiesStatelessComponent.__super__ = doom_StatelessComponent;
doom_PropertiesStatelessComponent.prototype = $extend(doom_StatelessComponent.prototype,{
	__class__: doom_PropertiesStatelessComponent
});
var dots_Html = function() { };
dots_Html.__name__ = ["dots","Html"];
dots_Html.parseNodes = function(html) {
	if(!dots_Html.pattern.match(html)) throw new js__$Boot_HaxeError("Invalid pattern \"" + html + "\"");
	var tmp;
	var _g = dots_Html.pattern.matched(1).toLowerCase();
	switch(_g) {
	case "tbody":case "thead":
		tmp = window.document.createElement("table");
		break;
	case "td":case "th":
		tmp = window.document.createElement("tr");
		break;
	case "tr":
		tmp = window.document.createElement("tbody");
		break;
	default:
		tmp = window.document.createElement("div");
	}
	var el = tmp;
	el.innerHTML = html;
	return el.childNodes;
};
dots_Html.parse = function(html) {
	return dots_Html.parseNodes(html)[0];
};
var dots_Query = function() { };
dots_Query.__name__ = ["dots","Query"];
dots_Query.first = function(selector,ctx) {
	return (ctx != null?ctx:dots_Query.doc).querySelector(selector);
};
var haxe_StackItem = { __ename__ : true, __constructs__ : ["CFunction","Module","FilePos","Method","LocalFunction"] };
haxe_StackItem.CFunction = ["CFunction",0];
haxe_StackItem.CFunction.toString = $estr;
haxe_StackItem.CFunction.__enum__ = haxe_StackItem;
haxe_StackItem.Module = function(m) { var $x = ["Module",1,m]; $x.__enum__ = haxe_StackItem; $x.toString = $estr; return $x; };
haxe_StackItem.FilePos = function(s,file,line) { var $x = ["FilePos",2,s,file,line]; $x.__enum__ = haxe_StackItem; $x.toString = $estr; return $x; };
haxe_StackItem.Method = function(classname,method) { var $x = ["Method",3,classname,method]; $x.__enum__ = haxe_StackItem; $x.toString = $estr; return $x; };
haxe_StackItem.LocalFunction = function(v) { var $x = ["LocalFunction",4,v]; $x.__enum__ = haxe_StackItem; $x.toString = $estr; return $x; };
var haxe_CallStack = function() { };
haxe_CallStack.__name__ = ["haxe","CallStack"];
haxe_CallStack.getStack = function(e) {
	if(e == null) return [];
	var oldValue = Error.prepareStackTrace;
	Error.prepareStackTrace = function(error,callsites) {
		var stack = [];
		var _g = 0;
		while(_g < callsites.length) {
			var site = callsites[_g];
			++_g;
			if(haxe_CallStack.wrapCallSite != null) site = haxe_CallStack.wrapCallSite(site);
			var method = null;
			var fullName = site.getFunctionName();
			if(fullName != null) {
				var idx = fullName.lastIndexOf(".");
				if(idx >= 0) {
					var className = HxOverrides.substr(fullName,0,idx);
					var methodName = HxOverrides.substr(fullName,idx + 1,null);
					method = haxe_StackItem.Method(className,methodName);
				}
			}
			stack.push(haxe_StackItem.FilePos(method,site.getFileName(),site.getLineNumber()));
		}
		return stack;
	};
	var a = haxe_CallStack.makeStack(e.stack);
	Error.prepareStackTrace = oldValue;
	return a;
};
haxe_CallStack.callStack = function() {
	try {
		throw new Error();
	} catch( e ) {
		haxe_CallStack.lastException = e;
		if (e instanceof js__$Boot_HaxeError) e = e.val;
		var a = haxe_CallStack.getStack(e);
		a.shift();
		return a;
	}
};
haxe_CallStack.exceptionStack = function() {
	return haxe_CallStack.getStack(haxe_CallStack.lastException);
};
haxe_CallStack.toString = function(stack) {
	var b = new StringBuf();
	var _g = 0;
	while(_g < stack.length) {
		var s = stack[_g];
		++_g;
		b.b += "\nCalled from ";
		haxe_CallStack.itemToString(b,s);
	}
	return b.b;
};
haxe_CallStack.itemToString = function(b,s) {
	switch(s[1]) {
	case 0:
		b.b += "a C function";
		break;
	case 1:
		var m = s[2];
		b.b += "module ";
		b.b += m == null?"null":"" + m;
		break;
	case 2:
		var line = s[4];
		var file = s[3];
		var s1 = s[2];
		if(s1 != null) {
			haxe_CallStack.itemToString(b,s1);
			b.b += " (";
		}
		b.b += file == null?"null":"" + file;
		b.b += " line ";
		b.b += line == null?"null":"" + line;
		if(s1 != null) b.b += ")";
		break;
	case 3:
		var meth = s[3];
		var cname = s[2];
		b.b += cname == null?"null":"" + cname;
		b.b += ".";
		b.b += meth == null?"null":"" + meth;
		break;
	case 4:
		var n = s[2];
		b.b += "local function #";
		b.b += n == null?"null":"" + n;
		break;
	}
};
haxe_CallStack.makeStack = function(s) {
	if(s == null) return []; else if(typeof(s) == "string") {
		var stack = s.split("\n");
		if(stack[0] == "Error") stack.shift();
		var m = [];
		var rie10 = new EReg("^   at ([A-Za-z0-9_. ]+) \\(([^)]+):([0-9]+):([0-9]+)\\)$","");
		var _g = 0;
		while(_g < stack.length) {
			var line = stack[_g];
			++_g;
			if(rie10.match(line)) {
				var path = rie10.matched(1).split(".");
				var meth = path.pop();
				var file = rie10.matched(2);
				var line1 = Std.parseInt(rie10.matched(3));
				m.push(haxe_StackItem.FilePos(meth == "Anonymous function"?haxe_StackItem.LocalFunction():meth == "Global code"?null:haxe_StackItem.Method(path.join("."),meth),file,line1));
			} else m.push(haxe_StackItem.Module(StringTools.trim(line)));
		}
		return m;
	} else return s;
};
var haxe_IMap = function() { };
haxe_IMap.__name__ = ["haxe","IMap"];
haxe_IMap.prototype = {
	__class__: haxe_IMap
};
var haxe_ds_Option = { __ename__ : true, __constructs__ : ["Some","None"] };
haxe_ds_Option.Some = function(v) { var $x = ["Some",0,v]; $x.__enum__ = haxe_ds_Option; $x.toString = $estr; return $x; };
haxe_ds_Option.None = ["None",1];
haxe_ds_Option.None.toString = $estr;
haxe_ds_Option.None.__enum__ = haxe_ds_Option;
var haxe_ds_StringMap = function() {
	this.h = { };
};
haxe_ds_StringMap.__name__ = ["haxe","ds","StringMap"];
haxe_ds_StringMap.__interfaces__ = [haxe_IMap];
haxe_ds_StringMap.prototype = {
	set: function(key,value) {
		if(__map_reserved[key] != null) this.setReserved(key,value); else this.h[key] = value;
	}
	,exists: function(key) {
		if(__map_reserved[key] != null) return this.existsReserved(key);
		return this.h.hasOwnProperty(key);
	}
	,setReserved: function(key,value) {
		if(this.rh == null) this.rh = { };
		this.rh["$" + key] = value;
	}
	,getReserved: function(key) {
		return this.rh == null?null:this.rh["$" + key];
	}
	,existsReserved: function(key) {
		if(this.rh == null) return false;
		return this.rh.hasOwnProperty("$" + key);
	}
	,remove: function(key) {
		if(__map_reserved[key] != null) {
			key = "$" + key;
			if(this.rh == null || !this.rh.hasOwnProperty(key)) return false;
			delete(this.rh[key]);
			return true;
		} else {
			if(!this.h.hasOwnProperty(key)) return false;
			delete(this.h[key]);
			return true;
		}
	}
	,keys: function() {
		var tmp;
		var _this = this.arrayKeys();
		tmp = HxOverrides.iter(_this);
		return tmp;
	}
	,arrayKeys: function() {
		var out = [];
		for( var key in this.h ) {
		if(this.h.hasOwnProperty(key)) out.push(key);
		}
		if(this.rh != null) {
			for( var key in this.rh ) {
			if(key.charCodeAt(0) == 36) out.push(key.substr(1));
			}
		}
		return out;
	}
	,__class__: haxe_ds_StringMap
};
var js__$Boot_HaxeError = function(val) {
	Error.call(this);
	this.val = val;
	this.message = String(val);
	if(Error.captureStackTrace) Error.captureStackTrace(this,js__$Boot_HaxeError);
};
js__$Boot_HaxeError.__name__ = ["js","_Boot","HaxeError"];
js__$Boot_HaxeError.__super__ = Error;
js__$Boot_HaxeError.prototype = $extend(Error.prototype,{
	__class__: js__$Boot_HaxeError
});
var js_Boot = function() { };
js_Boot.__name__ = ["js","Boot"];
js_Boot.getClass = function(o) {
	if((o instanceof Array) && o.__enum__ == null) return Array; else {
		var cl = o.__class__;
		if(cl != null) return cl;
		var name = js_Boot.__nativeClassName(o);
		if(name != null) return js_Boot.__resolveNativeClass(name);
		return null;
	}
};
js_Boot.__string_rec = function(o,s) {
	if(o == null) return "null";
	if(s.length >= 5) return "<...>";
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) t = "object";
	switch(t) {
	case "object":
		if(o instanceof Array) {
			if(o.__enum__) {
				if(o.length == 2) return o[0];
				var str2 = o[0] + "(";
				s += "\t";
				var _g1 = 2;
				var _g = o.length;
				while(_g1 < _g) {
					var i1 = _g1++;
					if(i1 != 2) str2 += "," + js_Boot.__string_rec(o[i1],s); else str2 += js_Boot.__string_rec(o[i1],s);
				}
				return str2 + ")";
			}
			var l = o.length;
			var i;
			var str1 = "[";
			s += "\t";
			var _g2 = 0;
			while(_g2 < l) {
				var i2 = _g2++;
				str1 += (i2 > 0?",":"") + js_Boot.__string_rec(o[i2],s);
			}
			str1 += "]";
			return str1;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e ) {
			haxe_CallStack.lastException = e;
			if (e instanceof js__$Boot_HaxeError) e = e.val;
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") return s2;
		}
		var k = null;
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		for( var k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) str += ", \n";
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "function":
		return "<function>";
	case "string":
		return o;
	default:
		return String(o);
	}
};
js_Boot.__nativeClassName = function(o) {
	var name = js_Boot.__toStr.call(o).slice(8,-1);
	if(name == "Object" || name == "Function" || name == "Math" || name == "JSON") return null;
	return name;
};
js_Boot.__resolveNativeClass = function(name) {
	return $global[name];
};
var lies_Store = function(reducer,initialState) {
	this.state = initialState;
	this.reducer = reducer;
	this.listeners = [];
};
lies_Store.__name__ = ["lies","Store"];
lies_Store.create = function(reducer,initialState) {
	return new lies_Store(reducer,initialState);
};
lies_Store.prototype = {
	dispatch: function(action) {
		if(null == action) throw new thx_Error("cannot dispatch a null action",null,{ fileName : "Store.hx", lineNumber : 20, className : "lies.Store", methodName : "dispatch"});
		var oldState = this.state;
		var value = this.reducer(oldState,action);
		this.state = value._0;
		this.invokeListeners(this.state,oldState,action);
		var _g = 0;
		var _g1 = value._1;
		while(_g < _g1.length) {
			var future = _g1[_g];
			++_g;
			future.then($bind(this,this.dispatch));
		}
	}
	,invokeListeners: function(currentState,oldState,action) {
		var _g = 0;
		var _g1 = this.listeners.slice();
		while(_g < _g1.length) {
			var listener = _g1[_g];
			++_g;
			listener(currentState,oldState,action);
		}
	}
	,subscribe: function(listener) {
		var _g = this;
		HxOverrides.remove(this.listeners,listener);
		this.listeners.push(listener);
		return function() {
			HxOverrides.remove(_g.listeners,listener);
		};
	}
	,__class__: lies_Store
};
var thx_Arrays = function() { };
thx_Arrays.__name__ = ["thx","Arrays"];
thx_Arrays.all = function(arr,predicate) {
	var $it0 = HxOverrides.iter(arr);
	while( $it0.hasNext() ) {
		var element = $it0.next();
		if(!predicate(element)) return false;
	}
	return true;
};
thx_Arrays.string = function(arr) {
	return "[" + arr.map(thx_Dynamics.string).join(", ") + "]";
};
var thx_Dynamics = function() { };
thx_Dynamics.__name__ = ["thx","Dynamics"];
thx_Dynamics.string = function(v) {
	{
		var _g = Type["typeof"](v);
		switch(_g[1]) {
		case 0:
			return "null";
		case 1:case 2:case 3:
			return "" + Std.string(v);
		case 4:
			return thx_Objects.string(v);
		case 6:
			var name = Type.getClassName(_g[2]);
			switch(name) {
			case "Array":
				return thx_Arrays.string(v);
			case "String":
				return thx_Strings.quote(v);
			case "Date":
				return HxOverrides.dateStr(v);
			default:
				return Std.string(v);
			}
			break;
		case 7:
			return thx_Enums.string(v);
		case 8:
			return "<unknown>";
		case 5:
			return "<function>";
		}
	}
};
var thx_Either = { __ename__ : true, __constructs__ : ["Left","Right"] };
thx_Either.Left = function(value) { var $x = ["Left",0,value]; $x.__enum__ = thx_Either; $x.toString = $estr; return $x; };
thx_Either.Right = function(value) { var $x = ["Right",1,value]; $x.__enum__ = thx_Either; $x.toString = $estr; return $x; };
var thx_Enums = function() { };
thx_Enums.__name__ = ["thx","Enums"];
thx_Enums.string = function(e) {
	var cons = e[0];
	var params = [];
	var _g = 0;
	var _g1 = e.slice(2);
	while(_g < _g1.length) {
		var param = _g1[_g];
		++_g;
		params.push(thx_Dynamics.string(param));
	}
	return cons + (params.length == 0?"":"(" + params.join(", ") + ")");
};
var thx_Error = function(message,stack,pos) {
	Error.call(this,message);
	this.message = message;
	if(null == stack) {
		var tmp;
		try {
			tmp = haxe_CallStack.exceptionStack();
		} catch( e ) {
			haxe_CallStack.lastException = e;
			if (e instanceof js__$Boot_HaxeError) e = e.val;
			tmp = [];
		}
		stack = tmp;
		if(stack.length == 0) {
			var tmp1;
			try {
				tmp1 = haxe_CallStack.callStack();
			} catch( e1 ) {
				haxe_CallStack.lastException = e1;
				if (e1 instanceof js__$Boot_HaxeError) e1 = e1.val;
				tmp1 = [];
			}
			stack = tmp1;
		}
	}
	this.stackItems = stack;
	this.pos = pos;
};
thx_Error.__name__ = ["thx","Error"];
thx_Error.__super__ = Error;
thx_Error.prototype = $extend(Error.prototype,{
	toString: function() {
		return this.message + "\nfrom: " + this.pos.className + "." + this.pos.methodName + "() at " + this.pos.lineNumber + "\n\n" + haxe_CallStack.toString(this.stackItems);
	}
	,__class__: thx_Error
});
var thx_Iterators = function() { };
thx_Iterators.__name__ = ["thx","Iterators"];
thx_Iterators.toArray = function(it) {
	var elements = [];
	while( it.hasNext() ) {
		var element = it.next();
		elements.push(element);
	}
	return elements;
};
var thx_Objects = function() { };
thx_Objects.__name__ = ["thx","Objects"];
thx_Objects.combine = function(first,second) {
	var to = { };
	var _g = 0;
	var _g1 = Reflect.fields(first);
	while(_g < _g1.length) {
		var field = _g1[_g];
		++_g;
		var value = Reflect.field(first,field);
		to[field] = value;
	}
	var _g2 = 0;
	var _g11 = Reflect.fields(second);
	while(_g2 < _g11.length) {
		var field1 = _g11[_g2];
		++_g2;
		var value1 = Reflect.field(second,field1);
		to[field1] = value1;
	}
	return to;
};
thx_Objects.string = function(o) {
	return "{" + Reflect.fields(o).map(function(key) {
		return "" + key + " : " + thx_Objects.string(Reflect.field(o,key));
	}).join(", ") + "}";
};
var thx_Strings = function() { };
thx_Strings.__name__ = ["thx","Strings"];
thx_Strings.isEmpty = function(value) {
	return value == null || value == "";
};
thx_Strings.quote = function(s) {
	if(s.indexOf("\"") < 0) return "\"" + s + "\""; else if(s.indexOf("'") < 0) return "'" + s + "'"; else return "\"" + StringTools.replace(s,"\"","\\\"") + "\"";
};
thx_Strings.trimCharsLeft = function(value,charlist) {
	var pos = 0;
	var _g1 = 0;
	var _g = value.length;
	while(_g1 < _g) {
		var i = _g1++;
		var tmp;
		var test = value.charAt(i);
		tmp = charlist.indexOf(test) >= 0;
		if(tmp) pos++; else break;
	}
	return value.substring(pos);
};
var thx_Timer = function() { };
thx_Timer.__name__ = ["thx","Timer"];
thx_Timer.immediate = function(callback) {
	return (function($this) {
		var $r;
		var id = setImmediate(callback);
		$r = function() {
			thx_Timer.clear(id);
		};
		return $r;
	}(this));
};
thx_Timer.clear = function(id) {
	clearTimeout(id);
	return;
};
var thx_error_AbstractMethod = function(posInfo) {
	thx_Error.call(this,"method " + posInfo.className + "." + posInfo.methodName + "() is abstract",null,posInfo);
};
thx_error_AbstractMethod.__name__ = ["thx","error","AbstractMethod"];
thx_error_AbstractMethod.__super__ = thx_Error;
thx_error_AbstractMethod.prototype = $extend(thx_Error.prototype,{
	__class__: thx_error_AbstractMethod
});
var thx_promise_Future = function() { };
thx_promise_Future.__name__ = ["thx","promise","Future"];
thx_promise_Future.prototype = {
	then: function(handler) {
		this.handlers.push(handler);
		this.update();
		return this;
	}
	,update: function() {
		{
			var _g = this.state;
			switch(_g[1]) {
			case 1:
				break;
			case 0:
				var index = -1;
				while(++index < this.handlers.length) this.handlers[index](_g[2]);
				this.handlers = [];
				break;
			}
		}
	}
	,__class__: thx_promise_Future
};
var todomvc_data_Reducers = function() { };
todomvc_data_Reducers.__name__ = ["todomvc","data","Reducers"];
todomvc_data_Reducers.todoApp = function(state,action) {
	return { visibilityFilter : todomvc_data_Reducers.visibilityFilter(state.visibilityFilter,action), todos : todomvc_data_Reducers.todos(state.todos,action)};
};
todomvc_data_Reducers.todos = function(state,action) {
	var tmp;
	switch(action[1]) {
	case 0:
		tmp = state.concat([{ text : action[2], completed : false}]);
		break;
	case 1:
		var index = action[2];
		var old = state[index];
		tmp = state.slice(0,index).concat([thx_Objects.combine(state[index],{ completed : !old.completed})]).concat(state.slice(index + 1));
		break;
	case 2:
		var index1 = action[2];
		tmp = state.slice(0,index1).concat(state.slice(index1 + 1));
		break;
	case 4:
		var index2 = action[2];
		tmp = state.slice(0,index2).concat([thx_Objects.combine(state[index2],{ text : action[3]})]).concat(state.slice(index2 + 1));
		break;
	case 5:
		tmp = state.filter(function(_) {
			return !_.completed;
		});
		break;
	case 6:
		var tmp1;
		var _e = state;
		tmp1 = function(predicate) {
			return thx_Arrays.all(_e,predicate);
		};
		var completed = !tmp1(function(_1) {
			return _1.completed;
		});
		tmp = state.map(function(_2) {
			return { text : _2.text, completed : completed};
		});
		break;
	default:
		tmp = state;
	}
	return tmp;
};
todomvc_data_Reducers.visibilityFilter = function(state,action) {
	var tmp;
	switch(action[1]) {
	case 3:
		tmp = action[2];
		break;
	default:
		tmp = state;
	}
	return tmp;
};
var todomvc_data_TodoAction = { __ename__ : true, __constructs__ : ["Add","Toggle","Remove","SetVisibilityFilter","UpdateText","ClearCompleted","ToggleAll"] };
todomvc_data_TodoAction.Add = function(text) { var $x = ["Add",0,text]; $x.__enum__ = todomvc_data_TodoAction; $x.toString = $estr; return $x; };
todomvc_data_TodoAction.Toggle = function(index) { var $x = ["Toggle",1,index]; $x.__enum__ = todomvc_data_TodoAction; $x.toString = $estr; return $x; };
todomvc_data_TodoAction.Remove = function(index) { var $x = ["Remove",2,index]; $x.__enum__ = todomvc_data_TodoAction; $x.toString = $estr; return $x; };
todomvc_data_TodoAction.SetVisibilityFilter = function(filter) { var $x = ["SetVisibilityFilter",3,filter]; $x.__enum__ = todomvc_data_TodoAction; $x.toString = $estr; return $x; };
todomvc_data_TodoAction.UpdateText = function(index,text) { var $x = ["UpdateText",4,index,text]; $x.__enum__ = todomvc_data_TodoAction; $x.toString = $estr; return $x; };
todomvc_data_TodoAction.ClearCompleted = ["ClearCompleted",5];
todomvc_data_TodoAction.ClearCompleted.toString = $estr;
todomvc_data_TodoAction.ClearCompleted.__enum__ = todomvc_data_TodoAction;
todomvc_data_TodoAction.ToggleAll = ["ToggleAll",6];
todomvc_data_TodoAction.ToggleAll.toString = $estr;
todomvc_data_TodoAction.ToggleAll.__enum__ = todomvc_data_TodoAction;
var todomvc_data_VisibilityFilter = { __ename__ : true, __constructs__ : ["ShowAll","ShowCompleted","ShowActive"] };
todomvc_data_VisibilityFilter.ShowAll = ["ShowAll",0];
todomvc_data_VisibilityFilter.ShowAll.toString = $estr;
todomvc_data_VisibilityFilter.ShowAll.__enum__ = todomvc_data_VisibilityFilter;
todomvc_data_VisibilityFilter.ShowCompleted = ["ShowCompleted",1];
todomvc_data_VisibilityFilter.ShowCompleted.toString = $estr;
todomvc_data_VisibilityFilter.ShowCompleted.__enum__ = todomvc_data_VisibilityFilter;
todomvc_data_VisibilityFilter.ShowActive = ["ShowActive",2];
todomvc_data_VisibilityFilter.ShowActive.toString = $estr;
todomvc_data_VisibilityFilter.ShowActive.__enum__ = todomvc_data_VisibilityFilter;
var todomvc_data_VisibilityFilters = function() { };
todomvc_data_VisibilityFilters.__name__ = ["todomvc","data","VisibilityFilters"];
todomvc_data_VisibilityFilters.filterVisibility = function(arr,filter) {
	var tmp;
	switch(filter[1]) {
	case 0:
		tmp = arr.slice();
		break;
	case 2:
		tmp = arr.filter(function(_) {
			return !_.completed;
		});
		break;
	case 1:
		tmp = arr.filter(function(_1) {
			return _1.completed;
		});
		break;
	}
	return tmp;
};
var todomvc_view_App = function(prop) {
	doom_PropertiesStatelessComponent.call(this,prop);
};
todomvc_view_App.__name__ = ["todomvc","view","App"];
todomvc_view_App.__super__ = doom_PropertiesStatelessComponent;
todomvc_view_App.prototype = $extend(doom_PropertiesStatelessComponent.prototype,{
	render: function() {
		var _g = this;
		var header = new todomvc_view_Header({ add : function(text) {
			_g.prop.dispatch(todomvc_data_TodoAction.Add(text));
		}});
		var body = new todomvc_view_Body({ setFilter : function(filter) {
			_g.prop.dispatch(todomvc_data_TodoAction.SetVisibilityFilter(filter));
		}, clearCompleted : function() {
			_g.prop.dispatch(todomvc_data_TodoAction.ClearCompleted);
		}, remove : function(index) {
			_g.prop.dispatch(todomvc_data_TodoAction.Remove(index));
		}, toggle : function(index1) {
			_g.prop.dispatch(todomvc_data_TodoAction.Toggle(index1));
		}, toggleAll : function() {
			_g.prop.dispatch(todomvc_data_TodoAction.ToggleAll);
		}, updateText : function(index2,text1) {
			_g.prop.dispatch(todomvc_data_TodoAction.UpdateText(index2,text1));
		}},this.prop.state);
		var tmp;
		var f = function() {
			body.update(_g.prop.state);
		};
		tmp = function(_,_1,_2) {
			f();
		};
		this.prop.subscribe(tmp);
		var tmp1;
		var children = [doom_NodeImpl.ComponentNode(header),doom_NodeImpl.ComponentNode(body)];
		tmp1 = doom__$Node_Node_$Impl_$.el("div",null,children,null);
		return tmp1;
	}
	,__class__: todomvc_view_App
});
var todomvc_view_Body = function(prop,state) {
	doom_PropertiesComponent.call(this,prop,state);
};
todomvc_view_Body.__name__ = ["todomvc","view","Body"];
todomvc_view_Body.__super__ = doom_PropertiesComponent;
todomvc_view_Body.prototype = $extend(doom_PropertiesComponent.prototype,{
	render: function() {
		var tmp;
		if(this.state.todos.length == 0) {
			var tmp1;
			var _g = new haxe_ds_StringMap();
			var value = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("display:none");
			if(__map_reserved.style != null) _g.setReserved("style",value); else _g.h["style"] = value;
			tmp1 = _g;
			tmp = doom__$Node_Node_$Impl_$.el("div",tmp1,[doom_NodeImpl.Comment(" " + "nothing to do yet" + " ")]);
		} else {
			var all = this.state.todos.length;
			var completed = todomvc_data_VisibilityFilters.filterVisibility(this.state.todos,todomvc_data_VisibilityFilter.ShowCompleted).length;
			var remaining = all - completed;
			var tmp2;
			var comp = new todomvc_view_List(this.prop,{ items : todomvc_data_VisibilityFilters.filterVisibility(this.state.todos,this.state.visibilityFilter), allCompleted : completed == 0});
			tmp2 = doom_NodeImpl.ComponentNode(comp);
			var tmp3;
			var comp1 = new todomvc_view_Footer(this.prop,{ remaining : remaining, filter : this.state.visibilityFilter, hasCompleted : completed > 0});
			tmp3 = doom_NodeImpl.ComponentNode(comp1);
			var children = [tmp2,tmp3];
			tmp = doom__$Node_Node_$Impl_$.el("div",null,children,null);
		}
		return tmp;
	}
	,__class__: todomvc_view_Body
});
var todomvc_view_Footer = function(prop,state) {
	doom_PropertiesComponent.call(this,prop,state);
};
todomvc_view_Footer.__name__ = ["todomvc","view","Footer"];
todomvc_view_Footer.__super__ = doom_PropertiesComponent;
todomvc_view_Footer.prototype = $extend(doom_PropertiesComponent.prototype,{
	render: function() {
		var tmp;
		var tmp3;
		var _g = new haxe_ds_StringMap();
		var value = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("todo-count");
		if(__map_reserved["class"] != null) _g.setReserved("class",value); else _g.h["class"] = value;
		tmp3 = _g;
		var attributes = tmp3;
		var children = this.getItemsLeftLabel();
		tmp = doom__$Node_Node_$Impl_$.el("span",attributes,children,null);
		var tmp1;
		var tmp4;
		var _g1 = new haxe_ds_StringMap();
		var value1 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("filters");
		if(__map_reserved["class"] != null) _g1.setReserved("class",value1); else _g1.h["class"] = value1;
		tmp4 = _g1;
		var attributes1 = tmp4;
		var tmp5;
		var tmp8;
		var tmp9;
		var _g7 = new haxe_ds_StringMap();
		var tmp10;
		var _g6 = new haxe_ds_StringMap();
		var value3 = this.isFilter(todomvc_data_VisibilityFilter.ShowAll);
		if(__map_reserved.selected != null) _g6.setReserved("selected",value3); else _g6.h["selected"] = value3;
		tmp10 = _g6;
		var value2 = doom__$AttributeValue_AttributeValue_$Impl_$.fromMap(tmp10);
		if(__map_reserved["class"] != null) _g7.setReserved("class",value2); else _g7.h["class"] = value2;
		var value4 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("#");
		if(__map_reserved.href != null) _g7.setReserved("href",value4); else _g7.h["href"] = value4;
		var tmp11;
		var f = $bind(this,this.handleClickFilter);
		tmp11 = function() {
			f(todomvc_data_VisibilityFilter.ShowAll);
		};
		var value5 = doom__$AttributeValue_AttributeValue_$Impl_$.fromHandler(tmp11);
		if(__map_reserved.click != null) _g7.setReserved("click",value5); else _g7.h["click"] = value5;
		tmp9 = _g7;
		var attributes2 = tmp9;
		var child1 = doom_NodeImpl.Text("All");
		tmp8 = doom__$Node_Node_$Impl_$.el("a",attributes2,null,child1);
		var child = tmp8;
		tmp5 = doom__$Node_Node_$Impl_$.el("li",null,null,child);
		var tmp6;
		var tmp12;
		var tmp13;
		var _g13 = new haxe_ds_StringMap();
		var tmp14;
		var _g12 = new haxe_ds_StringMap();
		var value7 = this.isFilter(todomvc_data_VisibilityFilter.ShowActive);
		if(__map_reserved.selected != null) _g12.setReserved("selected",value7); else _g12.h["selected"] = value7;
		tmp14 = _g12;
		var value6 = doom__$AttributeValue_AttributeValue_$Impl_$.fromMap(tmp14);
		if(__map_reserved["class"] != null) _g13.setReserved("class",value6); else _g13.h["class"] = value6;
		var value8 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("#/active");
		if(__map_reserved.href != null) _g13.setReserved("href",value8); else _g13.h["href"] = value8;
		var tmp15;
		var f1 = $bind(this,this.handleClickFilter);
		tmp15 = function() {
			f1(todomvc_data_VisibilityFilter.ShowActive);
		};
		var value9 = doom__$AttributeValue_AttributeValue_$Impl_$.fromHandler(tmp15);
		if(__map_reserved.click != null) _g13.setReserved("click",value9); else _g13.h["click"] = value9;
		tmp13 = _g13;
		var attributes3 = tmp13;
		var child3 = doom_NodeImpl.Text("Active");
		tmp12 = doom__$Node_Node_$Impl_$.el("a",attributes3,null,child3);
		var child2 = tmp12;
		tmp6 = doom__$Node_Node_$Impl_$.el("li",null,null,child2);
		var tmp7;
		var tmp16;
		var tmp17;
		var _g19 = new haxe_ds_StringMap();
		var tmp18;
		var _g18 = new haxe_ds_StringMap();
		var value11 = this.isFilter(todomvc_data_VisibilityFilter.ShowCompleted);
		if(__map_reserved.selected != null) _g18.setReserved("selected",value11); else _g18.h["selected"] = value11;
		tmp18 = _g18;
		var value10 = doom__$AttributeValue_AttributeValue_$Impl_$.fromMap(tmp18);
		if(__map_reserved["class"] != null) _g19.setReserved("class",value10); else _g19.h["class"] = value10;
		var value12 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("#/completed");
		if(__map_reserved.href != null) _g19.setReserved("href",value12); else _g19.h["href"] = value12;
		var tmp19;
		var f2 = $bind(this,this.handleClickFilter);
		tmp19 = function() {
			f2(todomvc_data_VisibilityFilter.ShowCompleted);
		};
		var value13 = doom__$AttributeValue_AttributeValue_$Impl_$.fromHandler(tmp19);
		if(__map_reserved.click != null) _g19.setReserved("click",value13); else _g19.h["click"] = value13;
		tmp17 = _g19;
		var attributes4 = tmp17;
		var child5 = doom_NodeImpl.Text("Completed");
		tmp16 = doom__$Node_Node_$Impl_$.el("a",attributes4,null,child5);
		var child4 = tmp16;
		tmp7 = doom__$Node_Node_$Impl_$.el("li",null,null,child4);
		var children1 = [tmp5,tmp6,tmp7];
		tmp1 = doom__$Node_Node_$Impl_$.el("ul",attributes1,children1,null);
		var footerContent = [tmp,tmp1];
		if(this.state.hasCompleted) {
			var tmp20;
			var tmp21;
			var _g20 = new haxe_ds_StringMap();
			var value14 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("clear-completed");
			if(__map_reserved["class"] != null) _g20.setReserved("class",value14); else _g20.h["class"] = value14;
			var value15 = doom__$AttributeValue_AttributeValue_$Impl_$.fromHandler($bind(this,this.handleClear));
			if(__map_reserved.click != null) _g20.setReserved("click",value15); else _g20.h["click"] = value15;
			tmp21 = _g20;
			var attributes5 = tmp21;
			var child6 = doom_NodeImpl.Text("Clear completed");
			tmp20 = doom__$Node_Node_$Impl_$.el("button",attributes5,null,child6);
			footerContent.push(tmp20);
		}
		var tmp2;
		var tmp22;
		var _g201 = new haxe_ds_StringMap();
		var value16 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("footer");
		if(__map_reserved["class"] != null) _g201.setReserved("class",value16); else _g201.h["class"] = value16;
		tmp22 = _g201;
		var attributes6 = tmp22;
		tmp2 = doom__$Node_Node_$Impl_$.el("footer",attributes6,footerContent,null);
		return tmp2;
	}
	,handleClear: function() {
		this.prop.clearCompleted();
	}
	,handleClickFilter: function(filter) {
		this.prop.setFilter(filter);
	}
	,isFilter: function(filter) {
		return Type.enumEq(this.state.filter,filter);
	}
	,getItemsLeftLabel: function() {
		var tmp;
		if(this.state.remaining == 1) {
			var tmp1;
			var child = doom_NodeImpl.Text("1");
			tmp1 = doom__$Node_Node_$Impl_$.el("strong",null,null,child);
			tmp = [tmp1,doom_NodeImpl.Text(" item left")];
		} else {
			var tmp2;
			var child1 = doom_NodeImpl.Text("" + this.state.remaining);
			tmp2 = doom__$Node_Node_$Impl_$.el("strong",null,null,child1);
			tmp = [tmp2,doom_NodeImpl.Text(" items left")];
		}
		return tmp;
	}
	,__class__: todomvc_view_Footer
});
var todomvc_view_Header = function(prop) {
	doom_PropertiesStatelessComponent.call(this,prop);
};
todomvc_view_Header.__name__ = ["todomvc","view","Header"];
todomvc_view_Header.__super__ = doom_PropertiesStatelessComponent;
todomvc_view_Header.prototype = $extend(doom_PropertiesStatelessComponent.prototype,{
	render: function() {
		var tmp;
		var tmp1;
		var _g = new haxe_ds_StringMap();
		var value = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("header");
		if(__map_reserved["class"] != null) _g.setReserved("class",value); else _g.h["class"] = value;
		tmp1 = _g;
		var attributes = tmp1;
		var tmp2;
		var child = doom_NodeImpl.Text("todos");
		tmp2 = doom__$Node_Node_$Impl_$.el("h1",null,null,child);
		var tmp3;
		var tmp4;
		var _g1 = new haxe_ds_StringMap();
		var value1 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("new-todo");
		if(__map_reserved["class"] != null) _g1.setReserved("class",value1); else _g1.h["class"] = value1;
		var value2 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("What needs to be done?");
		if(__map_reserved.placeholder != null) _g1.setReserved("placeholder",value2); else _g1.h["placeholder"] = value2;
		var value3 = doom__$AttributeValue_AttributeValue_$Impl_$.fromBool(true);
		if(__map_reserved.autofocus != null) _g1.setReserved("autofocus",value3); else _g1.h["autofocus"] = value3;
		var value4 = doom__$AttributeValue_AttributeValue_$Impl_$.fromEventHandler($bind(this,this.handleKeys));
		if(__map_reserved.keydown != null) _g1.setReserved("keydown",value4); else _g1.h["keydown"] = value4;
		tmp4 = _g1;
		var attributes1 = tmp4;
		tmp3 = doom__$Node_Node_$Impl_$.el("input",attributes1,null,null);
		var children = [tmp2,tmp3];
		tmp = doom__$Node_Node_$Impl_$.el("header",attributes,children,null);
		return tmp;
	}
	,handleKeys: function(e) {
		if(13 == e.which) {
			e.preventDefault();
			var value = this.getInputValueAndEmpty();
			if(thx_Strings.isEmpty(value)) return;
			this.prop.add(value);
		}
	}
	,getInputValueAndEmpty: function() {
		var el = this.element.querySelector("input");
		var value = StringTools.trim(el.value);
		el.value = "";
		return value;
	}
	,__class__: todomvc_view_Header
});
var todomvc_view_Item = function(prop,state) {
	doom_PropertiesComponent.call(this,prop,state);
};
todomvc_view_Item.__name__ = ["todomvc","view","Item"];
todomvc_view_Item.__super__ = doom_PropertiesComponent;
todomvc_view_Item.prototype = $extend(doom_PropertiesComponent.prototype,{
	render: function() {
		var tmp;
		var tmp1;
		var _g1 = new haxe_ds_StringMap();
		var tmp4;
		var _g = new haxe_ds_StringMap();
		var value1 = this.state.item.completed;
		if(__map_reserved.completed != null) _g.setReserved("completed",value1); else _g.h["completed"] = value1;
		var value2 = this.state.editing;
		if(__map_reserved.editing != null) _g.setReserved("editing",value2); else _g.h["editing"] = value2;
		tmp4 = _g;
		var value = doom__$AttributeValue_AttributeValue_$Impl_$.fromMap(tmp4);
		if(__map_reserved["class"] != null) _g1.setReserved("class",value); else _g1.h["class"] = value;
		var value3 = doom__$AttributeValue_AttributeValue_$Impl_$.fromHandler($bind(this,this.handleDblClick));
		if(__map_reserved.dblclick != null) _g1.setReserved("dblclick",value3); else _g1.h["dblclick"] = value3;
		tmp1 = _g1;
		var attributes = tmp1;
		var tmp2;
		var tmp5;
		var _g2 = new haxe_ds_StringMap();
		var value4 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("view");
		if(__map_reserved["class"] != null) _g2.setReserved("class",value4); else _g2.h["class"] = value4;
		tmp5 = _g2;
		var attributes1 = tmp5;
		var tmp6;
		var tmp9;
		var _g3 = new haxe_ds_StringMap();
		var value5 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("toggle");
		if(__map_reserved["class"] != null) _g3.setReserved("class",value5); else _g3.h["class"] = value5;
		var value6 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("checkbox");
		if(__map_reserved.type != null) _g3.setReserved("type",value6); else _g3.h["type"] = value6;
		var value7 = doom__$AttributeValue_AttributeValue_$Impl_$.fromBool(this.state.item.completed);
		if(__map_reserved.checked != null) _g3.setReserved("checked",value7); else _g3.h["checked"] = value7;
		var value8 = doom__$AttributeValue_AttributeValue_$Impl_$.fromHandler(($_=this.prop,$bind($_,$_.toggle)));
		if(__map_reserved.change != null) _g3.setReserved("change",value8); else _g3.h["change"] = value8;
		tmp9 = _g3;
		var attributes2 = tmp9;
		tmp6 = doom__$Node_Node_$Impl_$.el("input",attributes2,null,null);
		var tmp7;
		var child = doom_NodeImpl.Text(this.state.item.text);
		tmp7 = doom__$Node_Node_$Impl_$.el("label",null,null,child);
		var tmp8;
		var tmp10;
		var _g4 = new haxe_ds_StringMap();
		var value9 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("destroy");
		if(__map_reserved["class"] != null) _g4.setReserved("class",value9); else _g4.h["class"] = value9;
		var value10 = doom__$AttributeValue_AttributeValue_$Impl_$.fromHandler(($_=this.prop,$bind($_,$_.remove)));
		if(__map_reserved.click != null) _g4.setReserved("click",value10); else _g4.h["click"] = value10;
		tmp10 = _g4;
		var attributes3 = tmp10;
		tmp8 = doom__$Node_Node_$Impl_$.el("button",attributes3,null,null);
		var children1 = [tmp6,tmp7,tmp8];
		tmp2 = doom__$Node_Node_$Impl_$.el("div",attributes1,children1,null);
		var tmp3;
		var tmp11;
		var _g5 = new haxe_ds_StringMap();
		var value11 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("edit");
		if(__map_reserved["class"] != null) _g5.setReserved("class",value11); else _g5.h["class"] = value11;
		var value12 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString(this.state.item.text);
		if(__map_reserved.value != null) _g5.setReserved("value",value12); else _g5.h["value"] = value12;
		var value13 = doom__$AttributeValue_AttributeValue_$Impl_$.fromHandler($bind(this,this.handleBlur));
		if(__map_reserved.blur != null) _g5.setReserved("blur",value13); else _g5.h["blur"] = value13;
		var value14 = doom__$AttributeValue_AttributeValue_$Impl_$.fromEventHandler($bind(this,this.handleKeydown));
		if(__map_reserved.keyup != null) _g5.setReserved("keyup",value14); else _g5.h["keyup"] = value14;
		tmp11 = _g5;
		var attributes4 = tmp11;
		tmp3 = doom__$Node_Node_$Impl_$.el("input",attributes4,null,null);
		var children = [tmp2,tmp3];
		tmp = doom__$Node_Node_$Impl_$.el("li",attributes,children,null);
		return tmp;
	}
	,handleDblClick: function() {
		this.state.editing = true;
		this.update(this.state);
		this.getInput().select();
	}
	,handleBlur: function() {
		if(!this.state.editing) return;
		this.state.editing = false;
		var value = this.getInputValueAndTrim();
		if(thx_Strings.isEmpty(value)) this.prop.remove(); else this.prop.updateText(value);
	}
	,handleKeydown: function(e) {
		if(e.which != 13) return;
		this.handleBlur();
	}
	,getInput: function() {
		return this.element.querySelector("input.edit");
	}
	,getInputValueAndTrim: function() {
		var input = this.getInput();
		return input.value = StringTools.trim(input.value);
	}
	,__class__: todomvc_view_Item
});
var todomvc_view_List = function(prop,state) {
	doom_PropertiesComponent.call(this,prop,state);
};
todomvc_view_List.__name__ = ["todomvc","view","List"];
todomvc_view_List.__super__ = doom_PropertiesComponent;
todomvc_view_List.prototype = $extend(doom_PropertiesComponent.prototype,{
	render: function() {
		var tmp;
		var tmp1;
		var _g = new haxe_ds_StringMap();
		var value = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("main");
		if(__map_reserved["class"] != null) _g.setReserved("class",value); else _g.h["class"] = value;
		tmp1 = _g;
		var attributes = tmp1;
		var tmp2;
		var tmp5;
		var _g1 = new haxe_ds_StringMap();
		var value1 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("toggle-all");
		if(__map_reserved["class"] != null) _g1.setReserved("class",value1); else _g1.h["class"] = value1;
		var value2 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("checkbox");
		if(__map_reserved.type != null) _g1.setReserved("type",value2); else _g1.h["type"] = value2;
		var value3 = doom__$AttributeValue_AttributeValue_$Impl_$.fromBool(this.state.allCompleted);
		if(__map_reserved.checked != null) _g1.setReserved("checked",value3); else _g1.h["checked"] = value3;
		var value4 = doom__$AttributeValue_AttributeValue_$Impl_$.fromHandler(($_=this.prop,$bind($_,$_.toggleAll)));
		if(__map_reserved.change != null) _g1.setReserved("change",value4); else _g1.h["change"] = value4;
		tmp5 = _g1;
		var attributes1 = tmp5;
		tmp2 = doom__$Node_Node_$Impl_$.el("input",attributes1,null,null);
		var tmp3;
		var tmp6;
		var _g2 = new haxe_ds_StringMap();
		var value5 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("toggle-all");
		if(__map_reserved["for"] != null) _g2.setReserved("for",value5); else _g2.h["for"] = value5;
		tmp6 = _g2;
		var attributes2 = tmp6;
		var child = doom_NodeImpl.Text("Mark all as complete");
		tmp3 = doom__$Node_Node_$Impl_$.el("label",attributes2,null,child);
		var tmp4;
		var tmp7;
		var _g3 = new haxe_ds_StringMap();
		var value6 = doom__$AttributeValue_AttributeValue_$Impl_$.fromString("todo-list");
		if(__map_reserved["class"] != null) _g3.setReserved("class",value6); else _g3.h["class"] = value6;
		tmp7 = _g3;
		var attributes3 = tmp7;
		var tmp8;
		var _g4 = [];
		var _g6 = 0;
		var _g5 = this.state.items.length;
		while(_g6 < _g5) {
			var i = _g6++;
			var tmp9;
			var tmp10;
			var f = [($_=this.prop,$bind($_,$_.remove))];
			var a1 = [i];
			tmp10 = (function(a11,f1) {
				return function() {
					f1[0](a11[0]);
				};
			})(a1,f);
			var tmp11;
			var f2 = [($_=this.prop,$bind($_,$_.toggle))];
			var a12 = [i];
			tmp11 = (function(a13,f3) {
				return function() {
					f3[0](a13[0]);
				};
			})(a12,f2);
			var tmp12;
			var f4 = [($_=this.prop,$bind($_,$_.updateText))];
			var a14 = [i];
			tmp12 = (function(a15,f5) {
				return function(a2) {
					f5[0](a15[0],a2);
				};
			})(a14,f4);
			var comp = new todomvc_view_Item({ remove : tmp10, toggle : tmp11, updateText : tmp12},{ item : this.state.items[i], editing : false});
			tmp9 = doom_NodeImpl.ComponentNode(comp);
			_g4.push(tmp9);
		}
		tmp8 = _g4;
		var children1 = tmp8;
		tmp4 = doom__$Node_Node_$Impl_$.el("ul",attributes3,children1,null);
		var children = [tmp2,tmp3,tmp4];
		tmp = doom__$Node_Node_$Impl_$.el("section",attributes,children,null);
		return tmp;
	}
	,__class__: todomvc_view_List
});
function $iterator(o) { if( o instanceof Array ) return function() { return HxOverrides.iter(o); }; return typeof(o.iterator) == 'function' ? $bind(o,o.iterator) : o.iterator; }
var $_, $fid = 0;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $fid++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = function(){ return f.method.apply(f.scope, arguments); }; f.scope = o; f.method = m; o.hx__closures__[m.__id__] = f; } return f; }
if(Array.prototype.indexOf) HxOverrides.indexOf = function(a,o,i) {
	return Array.prototype.indexOf.call(a,o,i);
};
String.prototype.__class__ = String;
String.__name__ = ["String"];
Array.__name__ = ["Array"];
Date.prototype.__class__ = Date;
Date.__name__ = ["Date"];
if(Array.prototype.map == null) Array.prototype.map = function(f) {
	var a = [];
	var _g1 = 0;
	var _g = this.length;
	while(_g1 < _g) {
		var i = _g1++;
		a[i] = f(this[i]);
	}
	return a;
};
if(Array.prototype.filter == null) Array.prototype.filter = function(f1) {
	var a1 = [];
	var _g11 = 0;
	var _g2 = this.length;
	while(_g11 < _g2) {
		var i1 = _g11++;
		var e = this[i1];
		if(f1(e)) a1.push(e);
	}
	return a1;
};
var __map_reserved = {}

      // Production steps of ECMA-262, Edition 5, 15.4.4.21
      // Reference: http://es5.github.io/#x15.4.4.21
      if (!Array.prototype.reduce) {
        Array.prototype.reduce = function(callback /*, initialValue*/) {
          'use strict';
          if (this == null) {
            throw new TypeError('Array.prototype.reduce called on null or undefined');
          }
          if (typeof callback !== 'function') {
            throw new TypeError(callback + ' is not a function');
          }
          var t = Object(this), len = t.length >>> 0, k = 0, value;
          if (arguments.length == 2) {
            value = arguments[1];
          } else {
            while (k < len && ! k in t) {
              k++;
            }
            if (k >= len) {
              throw new TypeError('Reduce of empty array with no initial value');
            }
            value = t[k++];
          }
          for (; k < len; k++) {
            if (k in t) {
              value = callback(value, t[k], k, t);
            }
          }
          return value;
        };
      }
    ;
var scope = ("undefined" !== typeof window && window) || ("undefined" !== typeof global && global) || this;
if(!scope.setImmediate) scope.setImmediate = function(callback) {
	scope.setTimeout(callback,0);
};
var lastTime = 0;
var vendors = ["webkit","moz"];
var x = 0;
while(x < vendors.length && !scope.requestAnimationFrame) {
	scope.requestAnimationFrame = scope[vendors[x] + "RequestAnimationFrame"];
	scope.cancelAnimationFrame = scope[vendors[x] + "CancelAnimationFrame"] || scope[vendors[x] + "CancelRequestAnimationFrame"];
	x++;
}
if(!scope.requestAnimationFrame) scope.requestAnimationFrame = function(callback1) {
	var currTime = new Date().getTime();
	var timeToCall = Math.max(0,16 - (currTime - lastTime));
	var id = scope.setTimeout(function() {
		callback1(currTime + timeToCall);
	},timeToCall);
	lastTime = currTime + timeToCall;
	return id;
};
if(!scope.cancelAnimationFrame) scope.cancelAnimationFrame = function(id1) {
	scope.clearTimeout(id1);
};
if(typeof(scope.performance) == "undefined") scope.performance = { };
if(typeof(scope.performance.now) == "undefined") {
	var nowOffset = new Date().getTime();
	if(scope.performance.timing && scope.performance.timing.navigationStart) nowOffset = scope.performance.timing.navigationStart;
	scope.performance.now = (function($this) {
		var $r;
		var now = function() {
			return new Date() - nowOffset;
		};
		$r = now;
		return $r;
	}(this));
}
Doom.namespaces = (function($this) {
	var $r;
	var _g = new haxe_ds_StringMap();
	if(__map_reserved.svg != null) _g.setReserved("svg","http://www.w3.org/2000/svg"); else _g.h["svg"] = "http://www.w3.org/2000/svg";
	$r = _g;
	return $r;
}(this));
doom_HtmlNode.customEvents = thx__$Set_Set_$Impl_$.createString(["create","mount"]);
dots_Html.pattern = new EReg("[<]([^> ]+)","");
dots_Query.doc = document;
js_Boot.__toStr = {}.toString;
Main.main();
})(typeof console != "undefined" ? console : {log:function(){}}, typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);

//# sourceMappingURL=app.js.map